README.md

I made an ActiveRecord adapter for Flipper: https://github.com/bgentry/flipper-activerecord
At the moment, it specifically targets Rails 4.2 or higher (due to the use of foreign keys).
This PR adds a link to it in the Flipper readme.

add link to flipper-activerecord

---

README.md

@bgentry prefers to keep ttps://github.com/bgentry/flipper-activerecord clean for Rails 4 (makes sense), so I've created a fork that works with Rails 3.2. Add link in the docs to that version.

Link to ActiveRecord 3 adapter.

---

Gemfile
lib/flipper/instrumentation/log_subscriber.rb

This is a workaround for a Rails bug that by default delegate the logger to ActiveSupport::LogSubscriber.
See https://github.com/jnunemaker/flipper/issues/29#issuecomment-75052342 for more information.
Fixes #29.

Define Flipper::Instrumentation::LogSubscriber#logger

---

lib/flipper/adapters/memory.rb

An adapter's `#clear` method is supposed to return true according to the specs.
/cc @rsanheim

Make Adapters::Memory#clear conform to expectations

---

lib/flipper/instrumentation/subscriber.rb

I noticed this method while profiling `Feature#enabled?`. Turns out we can speed it up without hurting readability by using `chomp` instead of `gsub`.
$ cat bench.rb
require 'benchmark'
Benchmark.bm do |x|
x.report("gsub ") { 100000.times { %w[enabled enabled?].each { |str| str.to_s.gsub(/\?$/, '') } } }
x.report("chomp") { 100000.times { %w[enabled enabled?].each { |str| str.to_s.chomp('?') } } }
end
$ ruby bench.rb
user     system      total        real
gsub   0.270000   0.010000   0.280000 (  0.273812)
chomp  0.070000   0.000000   0.070000 (  0.071246)
I tried a lot of other variations (`\z` instead of `$`, `gsub!`, `sub`, `sub!`, `slice`, `slice!`, `chomp!`) and this was the fastest.
I doubt this will have a big effect on Flipper's performance overall, but there doesn't seem to be …

Speed up Subscriber#strip_trailing_question_mark

---

lib/flipper/feature.rb
lib/flipper/instrumenters/memory.rb

Some instrumentation services don't pass the original payload straight through to the block (e.g., they might copy it and add their own information to it). With those instrumenters it's important to use the payload passed to the block rather than the original payload or information added by the block might get lost.
/cc @jnunemaker @rsanheim

Use the instrumented block's payload, not the original payload

---

flipper.gemspec

Clean up some warnings when building the gem:
```
Building flipper.gemspec
WARNING:  licenses is empty, but is recommended.  Use a license abbreviation from:
http://opensource.org/licenses/alphabetical
WARNING:  description and summary are identical
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
```

Fix up gemspec

---

lib/flipper/feature.rb
lib/flipper/gate.rb
lib/flipper/gates/actor.rb
lib/flipper/gates/boolean.rb
lib/flipper/gates/group.rb
lib/flipper/gates/percentage_of_actors.rb
lib/flipper/gates/percentage_of_time.rb
spec/flipper/feature_spec.rb
spec/flipper/gates/actor_spec.rb
spec/flipper/gates/boolean_spec.rb
spec/flipper/gates/group_spec.rb
spec/flipper/gates/percentage_of_actors_spec.rb
spec/flipper/gates/percentage_of_time_spec.rb

I found it confusing. Sometimes it would say enabled for 15% of actors, 15% of the time which meant 15% of actors and 15% of time but looked like 15% of actors 15% of the time.
Additionally, I’d like to make description available as a user defined thing describing what the feature is used for.
Fixes #56

Ax description

---

lib/flipper/feature.rb
lib/flipper/gates/group.rb
lib/flipper/types/actor.rb
spec/flipper/feature_spec.rb
spec/flipper/gates/group_spec.rb
spec/flipper/instrumentation/log_subscriber_spec.rb
spec/flipper/types/actor_spec.rb

It was split before based on what method you called and what you passed in. Now it always instruments a flipper type for consistency sake.

Always instrument flipper type

---

examples/redis/namespaced.rb

It took me a while to realize that the way to namespace a redis adapter is to pass in a namespaced redis object as the client. I should have read the comment earlier but it took me a while to find. I created this example so that hopefully it would help other people realize how to do this quicker and also have an example to go off.

adding an example of namespacing for the redis adapter

---

spec/flipper/adapters/mongo_spec.rb

Hi!
I was struggling to run the specs due my mongodb is running in a specific host, so I did something similar to the Redis adapter spec.
So to run the specs you can execute:
```
BOXEN_MONGODB_HOST=my_mongodb_host bundle exec rspec
```
Thanks!

Add optional env vars to connect with mongodb

---

spec/flipper/adapters/mongo_spec.rb

Per discussion in #87.
This is apparently the timeout we need to make tests fail faster when mongo isn't running.

Add timeout to Mongo test

---

lib/flipper/ui.rb
lib/flipper/ui/action.rb
lib/flipper/ui/views/layout.erb
spec/flipper/ui/action_spec.rb
spec/flipper/ui_spec.rb

An alternate approach that uses the existing breadcrumbs and also has a really sensible default.

Add a link back to the app via a breadcrumb.

---

.travis.yml
Gemfile
Gemfile-rails32
Rakefile
docs/active_record/README.md
examples/active_record/basic.rb
examples/active_record/internals.rb
flipper-active_record.gemspec
lib/flipper-active_record.rb
lib/flipper/adapters/active_record.rb
lib/flipper/spec/shared_adapter_specs.rb
lib/generators/flipper/active_record_generator.rb
lib/generators/flipper/templates/migration.rb
script/test
spec/flipper/adapters/active_record_spec.rb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/boolean_gate_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/actions/gate_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb
spec/flipper/ui/actions/percentage_of_actors_gate_spec.rb
spec/flipper/ui/actions/percentage_of_time_gate_spec.rb
spec/flipper/ui_spec.rb
test/generators/flipper/active_record_generator_test.rb
test/helper.rb

I initially didn't want to maintain or provide this as I wasn't sure it was a good idea, but I ended up making and using one on a side project so I might as well drop it in core. This is similar to the existing active record adapters, but doesn't use foreign keys or anything rails 4 specific. Should work with rails 3 as well, but I need to get a travis ci matrix going for rails 3 just to be sure.

Add Core Activerecord Adapter

---

lib/generators/flipper/active_record_generator.rb

Before this fix I was getting `[WARNING] Could not load generator "generators/flipper/active_record_generator". Error: uninitialized constant Flipper::Rails::Generators.` when running the migration alongside a small Rails wrapper I'm writing: https://github.com/bmulholland/flipper-rails

Fix uninitialized constant Flipper::Rails::Generators

---

lib/flipper/spec/shared_adapter_specs.rb
spec/flipper/adapters/pstore_spec.rb

Fixes #104 by ensuring that any adapter passes this. clear should only remove gates, not the feature itself.

Explicitly test that feature remains after adapter clear

---

.travis.yml
flipper-ui.gemspec
lib/flipper/adapters/active_record.rb
lib/flipper/ui.rb
script/test

Require for folks trying out Rails 5. I can tweak the build matrix to run the tests against rack `2.0.0.alpha` in the same way that the repository supports Rails 3.2 + 4.2 if we want to go that road.

Add support for Rack 2.

---

lib/flipper/adapters/read_only.rb
spec/flipper/adapters/read_only_spec.rb

This adds read only adapter for situations where the application uses flipper but the UI runs separate and handles the updating.
fyi @dangerp
closes #91
closes #92

Add read only adapter

---

lib/flipper/ui/assets/stylesheets/application.scss
lib/flipper/ui/public/css/application.css
lib/flipper/ui/views/feature.erb

Sometimes people get confused and think that percentage of actors and time work in tandem. They don't. They work completely independently of each other.
A small help note below them to explain the difference. I don't love repeating basically the same text in two spots, but I tried a few things and went with this. Open to better ideas if anyone has any.
The original suggestion took too much focus from the actual form controls.
I also tried a tooltip, but it felt too hidden and didn't allow for much text. 
cc @olivierlacan for thoughts as he brought it up here https://github.com/jnunemaker/flipper/issues/103

Clarify percentage of time/actor functionality being independent in UI

---

lib/flipper/types/group.rb
spec/flipper/types/group_spec.rb
spec/integration_spec.rb

Ruby general is ok with truthy and falsey values over explicitly true and false. Flipper was different and expected exactly true to be returned by the flipper group match block. 
Allow truthy to work. This means that blocks that return truthy values which previously would have returned false will now return true.
Fixes #110

Allow truthy and falsey values to be enough in group match blocks

---

lib/flipper/feature.rb
lib/flipper/instrumentation/log_subscriber.rb
lib/flipper/instrumentation/subscriber.rb
spec/flipper/instrumentation/log_subscriber_spec.rb
spec/flipper/instrumentation/metriks_subscriber_spec.rb
spec/flipper/instrumentation/statsd_subscriber_spec.rb

Feature operations is what I’ve found most useful. I haven’t actually looked at gate operation metrics ever and they add N + 1 instrument calls (which aren’t free) where N is the number of gates. If we really do need this, let me know. Perhaps we can just tack information on the feature operation instrumentation (trade bigger payload for fewer instrument calls).

Remove instrumentation for gate operations

---

lib/flipper/api/action.rb
lib/flipper/api/middleware.rb
lib/flipper/api/v1/actions/boolean_gate.rb
lib/flipper/api/v1/actions/feature.rb
lib/flipper/api/v1/decorators/feature.rb
lib/flipper/api/v1/decorators/gate.rb
spec/flipper/api/v1/actions/feature_spec.rb

Add /feature endpoint
adds:
GET, DELETE actions
* Feature Decorator
* Gate Decorator
* specs
---------------------------------------------------------------------------------------------------------------------
Have two questions (answered - thank you):
1. lib/flipper/gate.rb:17
states that ```key``` is a private method.  Should json from ```get``` only return name and value, and omit key?
2. I want to return a 404 if a get request fails to find a feature, however flipper/dsl defines a public function ```[]``` and aliases it to ```#feature```  which creates an new feature if it doesn't already exist.  What do you think about changing this functionality so that the ```feature``` still creates a new feature, but ```[]``` will return nil if no feature exists for a given key?  I know this is …

Api /feature endpoint

---

lib/flipper/adapters/active_record.rb
lib/flipper/spec/shared_adapter_specs.rb

Choosing a second (or additional) percentage creates an additional row in the feature_gates table.  The one that is used is arbitrary, typically the first one created.
Additionally, if a user chooses a percentage for a feature that was previously chosen, this will create an exception.
The fix should work in rails 3.2 and 4.x.

Allow changing of actor or percentage gates in active_record adapter

---

lib/flipper/adapters/active_record.rb
lib/flipper/spec/shared_adapter_specs.rb

refs #122. This takes a bit different approach and also fixes the issue for disable. Instead of first or initialize by which could race we use a transaction to delete all and create. Instead of still possibly ending up with dups this approach should mean we just let last write win. I think…

Disallow multiple gate values for integer values in AR adapter

---

lib/flipper/ui.rb
lib/flipper/ui/views/layout.erb
spec/flipper/ui_spec.rb

For our project, we wanted to remove the Add Feature button from the UI.  We made it configurable in case others wanted to do remove it as well.
The code is similar to `application_breadcrumb_href`.  The button can be removed by:
`Flipper::UI.remove_add_feature_button = true`

make add feature button optional

---

Rakefile
test/helper.rb

First step towards #55 
*Run Mintests with `rake test`
*Run Rspecs with `rake spec`
*Run all specs with `rake`
Makes it really easy to add files to the LOAD_PATH before running specs and no longer have to execute shell commands to run minitests.  We can put the minitest shared_example type tests under `/test`
http://docs.ruby-lang.org/en/2.1.0/Rake/TestTask.html

Add Rake::TestTask

---

lib/flipper/api/v1/actions/feature.rb
lib/flipper/dsl.rb
lib/flipper/feature.rb
spec/flipper/dsl_spec.rb
spec/flipper/feature_spec.rb

I thought it might make sense for it to be available on the feature level:
```rb
flipper[:feature].remove
```

add #remove method to the Feature class

---

lib/flipper/middleware/memoizer.rb

Minor fix - looks like accidentally forgot to change doc to say Memoizer instead of UI

change doc to reference memoizer middleware instead of UI middleware

---

Changelog.md
lib/flipper/test/shared_adapter_test.rb
test/adapters/active_record_test.rb
test/adapters/memory_test.rb
test/adapters/mongo_test.rb
test/adapters/pstore_test.rb
test/adapters/redis_test.rb

This moves shared adapter tests under Flipper::Test to match the directory structure and avoid clobbering top level modules in apps that use flipper.
cc @AlexWheeler 
fixes #135

Shared adapter module namespace

---

docs/Adapters.md

Adds documentation for shared MiniTests

Add shared mini test doc to Adapters docs

---

Changelog.md
lib/flipper/adapters/instrumented.rb
lib/flipper/adapters/memoizable.rb
lib/flipper/adapters/operation_logger.rb
lib/flipper/dsl.rb
lib/flipper/feature.rb
lib/flipper/gate_values.rb
lib/flipper/instrumentation/subscriber.rb
lib/flipper/version.rb
spec/flipper/adapters/instrumented_spec.rb
spec/flipper/adapters/memoizable_spec.rb
spec/flipper/adapters/operation_logger_spec.rb
spec/flipper/dsl_spec.rb
spec/flipper/instrumentation/log_subscriber_spec.rb
spec/flipper/instrumentation/metriks_subscriber_spec.rb
spec/flipper/instrumentation/statsd_subscriber_spec.rb

* some constant ❄️ 'ing
* ensure memoizable, instrumented and operation logger delegate missing methods; the reason is that we (GitHub) use some custom adapters that have custom methods and call those on flipper.adapter.some_custom_method and those started failing when I tried to upgrade to 0.8 (which removed decorator)
* instrumenting adapters is now off by default, there was no way to opt out, since this instrumentation isn't insanely useful i'd rather make it opt in, super easy to do so, people can just use the instrumented adapter around their current one (ie: Flipper::Adapters::Instrumented.new(Flipper::Adapters::ActiveRecord.new)).
* dropped a few string allocations
I'll bump to 0.9 since the adapter instrumentation stuff is kind of breaking.

Instrumentation Tweaks

---

README.md
docs/Optimization.md

#140 add documentation for Dalli adapter.  I think it makes most sense to put this under Optimization as opposed to adapters since it's really an optimization and meant to wrap a primary database adapter.  I decided to use the header `Cache Adapters` because we might have more adapters used just for caching in the future.  Curious to hear thoughts and if the example / wording could be improved

Dalli cache adapter optimization documentation

---

lib/flipper/api/action.rb
lib/flipper/ui/action.rb
spec/flipper/api/action_spec.rb
spec/flipper/ui/action_spec.rb

Just a safety precaution since we do respond to and send. We really only want certain methods to "work" for performing an action so let's be explicit.

Whitelist valid request method names

---

.travis.yml
flipper-active_record.gemspec
script/test

Now that Rails 5 is out the gemspec for the AR adapter needed to be adjusted. Additionally, I updated all the test/ci stuff to run against rails 5.

Adjust gemspec and test/ci for Rails 5

---

lib/flipper/api/middleware.rb
lib/flipper/api/v1/actions/features.rb
spec/flipper/api/v1/actions/features_spec.rb

addresses #130 
Having thoughts that might be better to return something like:
```
features = flipper.features.map { |feature|
{ feature: Decorators::Feature.new(feature).as_json }
}
json_response({ features: features })
```
so could add some non-breaking updates to response if wanted to (and add it to /feature), but then I also thought this works and not sure what else would want to add
i.e.
```
features = flipper.features.map {|feature|
{ feature: feature: Decorators::Feature.new(feature).as_json, some_other_data: "..." }
}
```

Api features endpoint

---

lib/flipper/instrumentation/statsd_subscriber.rb

Nothing statsd specific is referenced other than the client, but that is just through the class var so no need to require this.

Stop requiring statsd in subscriber

---

lib/flipper/api/v1/actions/features.rb
spec/flipper/api/v1/actions/features_spec.rb

Looks like master is failing, #154 should fix it. Once merged I can rebase
* endpoint to add a feature
I decided to make the parameter 'name' since that matches the signature for `Flipper::DSL#feature`, which takes a name as an argument.
I decided to use 422 because RFC 4918 describes it as:
The 422 (Unprocessable Entity) status code means the server
understands the content type of the request entity (hence a
415(Unsupported Media Type) status code is inappropriate), and the
syntax of the request entity is correct (thus a 400 (Bad Request)
status code is inappropriate) but was unable to process the contained
instructions.  For example, this error condition may occur if an XML
request body contains well-formed (i.e., syntactically correct), but
semantically erroneous, XML instructions.
I …

POST /api/v1/features - add feature endpoint

---

flipper-ui.gemspec
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/boolean_gate_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/actions/gate_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb
spec/flipper/ui/actions/percentage_of_actors_gate_spec.rb
spec/flipper/ui/actions/percentage_of_time_gate_spec.rb
spec/flipper/ui_spec.rb

rack-protection no longer works with session["_csrf_token"], but does work with session[:csrf] in both 1.5.3 and 2.0.0.beta2 so I'm switching to :csrf. This also uses the random key method if it exists. Probably didn't need to do that, but it doesn't hurt anything.
refs #153

rack-protection 2.0.0 support

---

docs/Adapters.md

Looks like its safe to say active_record adapter is working with Rails 5 since active_record.gemspec now has dependency at ">= 3.2", "< 6" and Travis is testing Rails5 and changelog says support as of Flipper-0.9.1 🎉

display support for active_record adapter Rails 5

---

docs/active_record/README.md

*Clearly defines what tables are generated by default, making it more obvious what the generator is actually doing which I think leads to an easier onboarding process for new flipper users

Updates active_record adaptor generator docs

---

lib/flipper/adapters/active_record.rb

fixes #161 
* rails 3 does not allow mass assignment.  This makes sure the active record adapter does not mass assign attributes

do not use mass assignment anymore for active record adapter

---

README.md
docs/api/README.md

I was looking at using the `flipper-api` but found that it lacked documentation so while documenting it for my own purposes, I decided it'd be better to contribute upstream. I've documented all of the API endpoints that currently exist.
Note: I wasn't sure if a `Usage` section was necessary or not as it'd be virtually the same as that of `flipper-ui` in terms of mounting, etc. so I left that out for now. But it is probably worth noting in some way as the `/flipper-api` path used in the documentation examples assumes a mount point so I'm curious what your thoughts are on that.
Thanks!

add flipper-api documentation

---

lib/flipper/ui.rb
spec/flipper/ui_spec.rb

Mounting a v0.9.2 `Flipper::UI.app` `Rack::Builder` instance in a
v4.2.7.1 Rails `config/routes.rb` file and running `bin/rake routes` was
resulting in the following error.
rake aborted!
NoMethodError: undefined method `+' for Flipper::UI:Module
/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/inspector.rb:54:in `reqs'
/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/inspector.rb:128:in `block in collect_routes'
/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/inspector.rb:122:in `collect'
/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/inspector.rb:122:in `collect_routes'
/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/inspector.rb:89:in `format'
/gems/railties-4.2.7.1/lib/rails/tasks/routes.rake:6:in `block in <top (required)>'
This was because the `Rack::Builder` …

Make Flipper::UI.app.inspect return a String

---

lib/flipper/api/v1/actions/boolean_gate.rb
spec/flipper/api/v1/actions/boolean_gate_spec.rb

* this is convention we're going for with api gates
`POST api/v1/features/:feature_name/:gate_name # enable`
`DELETE api/v1/features/:feature_name/:gate_name # disable`
discussion about this can be found at #166

changes boolean gate route to api/v1/features/boolean

---

lib/flipper/api/middleware.rb
lib/flipper/api/v1/actions/groups_gate.rb
spec/flipper/api/v1/actions/groups_gate_spec.rb

References #165 
Endpoint for enabling/disabling feature for a given group. I'm thinking we follow the naming convention with Boolean gate of using *route*/(enable | disable).
*api/v1/features/:feature_name/groups/:group_name/enable*
*api/v1/features/:feature_name/groups/:group_name/disable*
Given a feature *logging* and a group *admins*
`PUT api/v1/features/logging/groups/admins/enable # enables logging feature for admins group`
`PUT api/v1/features/logging/groups/admins/disable # disables logging feature for admins group`
I'm trying to think about how to handle errors:
it would be nice to know if you requested an unknown feature or non-registered group rather than just a generic 404.  Still haven't decided on an exception api for the api, but maybe:
{status: *http_code*, message: …

Add Api V1 groups gate endpoint

---

lib/flipper/api/v1/actions/boolean_gate.rb
spec/flipper/api/v1/actions/boolean_gate_spec.rb

All successful gate endpoint actions will return:
1.  200 http status code
2. decorated feature
* this is the convention that all gates (enable/disable) endpoints will follow

update api v1 boolean gate endpoint responses to follow conventions for gate endpoints

---

lib/flipper/api/action.rb
lib/flipper/api/error_response.rb
lib/flipper/api/v1/actions/groups_gate.rb
spec/flipper/api/action_spec.rb

* moves error codes / as_json logic into descriptive module and provides `json_error_response` method to all actions
* `json_error_response` is very clear you're rendering an error as opposed to a successful response
* adds specs
* updates Groups Gate endpoint to use this error response format
we get to take advantage of Ruby's `fetch` so a KeyError will be raised if pass in an invalid error key, and also I like this approach because we get an api on top of directly accessing the hash, just use json_error_response(:error_key, status) and everything just works

Makes Api V1 error responses reusable and standardized

---

lib/flipper/api/error_response.rb
lib/flipper/api/middleware.rb
lib/flipper/api/v1/actions/percentage_of_actors_gate.rb
spec/flipper/api/v1/actions/percentage_of_actors_gate_spec.rb

* POST / DELETE request to enable / disable
* *send parameter 'percentage' to request percentage to enable 
* only POST requires a percentage parameter to be passed with request
* percentage_invalid raised and returned if percentage param is missing or not <= 100.  I like the name because it keeps with the convention:
:{ thing } _ { error_description }
i.e.
:{feature} _ {not_found}
:{group} _ {not_registered}
:{percentage } _ {invalid}
* uses regex to make sure percentage parameter is a number <= 100.  This is powerful because it handles all the edge cases, and we can keep it in the ensure_valid_post_params method
1. parameter is missing
2. parameter is empty string or nil
3. parameter is out of range
* adds specs

Api V1 percentage_of_actors gate endpoint

---

lib/flipper/api.rb
lib/flipper/api/actor.rb
lib/flipper/api/error_response.rb
lib/flipper/api/middleware.rb
lib/flipper/api/v1/actions/actors_gate.rb
spec/flipper/api/v1/actions/actors_gate_spec.rb

completes #169 
* POST / DELETE to enable disable with 'flipper_id' parameter
* adds specs
* adds Fliper::Api::Actor shim just like UI
Returns error if flipper_id parameter is missing or nil.  Flipper allows enabling an actor with a nil flipper_id, and I thought about allowing this and only rendering error on missing flipper_id parameter, but the more I think about it I don't think its ideal for a user to do this.  A flipper id should ideally be unique.  It opens the door for accidentally enabling a feature for anything with a nil flipper_id and users wanting to do this are better off using the group gate right?  Let me know your thoughts
Figured its easier to review small PRs so will update invalid error responses to 422, or can do it in this PR as a separate commit if you'd like

add api v1 actors gate endpoint

---

lib/flipper/api/error_response.rb
spec/flipper/api/v1/actions/actors_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_actors_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_time_gate_spec.rb

Prefer 422 to 400 http status code for some errors
- flipper_id_invalid
- percentage_invalid
Was using 400, but 422 is much more specific and describes an error in
the request message as opposed to a syntax error
RFC describing 422
https://tools.ietf.org/html/rfc4918#section-11.2
"For example, this error condition may occur if an XML
request body contains well-formed (i.e., syntactically correct), but
semantically erroneous, XML instructions"

use 422 status code for flipper_id_invalid, perecentage_invalid

---

docs/api/README.md

since the first docs created we've updated how we're structuring gate endpoints. For example `PUT /features/:name/enable` is now `POST features/:name/boolean`.  And #183 if you like it will have adding a feature return a 200 and a decorated feature over no content so this just makes sure docs are up to date.
This is just first step to make sure docs are up to date with the current state of the api.  Would like to continue to improve them.

updates api v1 docs

---

lib/flipper/api/error_response.rb
lib/flipper/api/v1/actions/feature.rb
lib/flipper/api/v1/actions/features.rb
spec/flipper/api/v1/actions/feature_spec.rb
spec/flipper/api/v1/actions/features_spec.rb

/feature, /features endpoints were built before ErrorResponse so now instead of `json_response({}, 404)` we can use `json_error_response(:feature_not_found)`.  With this change any api error handling code uses json_error_response.
POST /features will now return a 200 response (was 204) with the decorated feature as the body.  I think this is more useful for any clients and is similar to what we're doing for enabling / disabling gates
DELETE /features still returns a 204, was thinking it might be nice to return the same response as GET /features, but it might be unnecessary to query/serialize all that every time you just want to delete something
Adds new ErrorResponse `:name_invalid`.  Thought about calling it `:feature_name_invalid`, but I figure `:name_invalid` is generic enough where it …

use json_error_response for /feature /features

---

docs/api/README.md

* documents enabling / disabling groups gate
* haven't documented errors yet
* fixes typo on the boolean docs 
* adds json block to the boolean response so it renders correctly

docs for Api v1 groups gate endpoint

---

lib/flipper/spec/shared_adapter_specs.rb

RSpec ships with disable_monkey_patching! set to true these days, so it's a good practice to prefix top-level blocks with the RSpec namespace. In my case, I have a custom adapter that tries to pull these shared examples in, but because of my RSpec config, it blows up.
See https://www.relishapp.com/rspec/rspec-core/v/3-0/docs/configuration/zero-monkey-patching-mode

Make shared_adapter_specs work with disable_monkey_patching setting

---

lib/flipper/spec/shared_adapter_specs.rb
spec/flipper/middleware/memoizer_spec.rb
spec/helper.rb

As pointed out in #188 RSpec >= 3.0 wants to avoid monkey patching.  This will help guide filpper spec code in the right direction by not allowing monkey patched methods

disables RSpec monkey patching

---

lib/flipper-active_record.rb

This prevents overwriting the `belongs_to_required_by_default` setting in Rails 5, as described in #129

Wait for ActiveSupport to tell us when active_record is loaded

---

lib/flipper/ui/views/feature.erb

Hi! Thanks so much for working on this. We just set it up internally and are loving it.
Although the Delete button is red and scary, I still found myself a bit surprised when clicking "Delete" didn't require an extra confirmation step. This adds a simple JavaScript dialog to be confirmed before the delete form is submitted.

Show confirmation dialog when deleting a feature

---

docs/api/README.md
lib/flipper/api/error_response.rb
spec/flipper/api/action_spec.rb
spec/flipper/api/v1/actions/actors_gate_spec.rb
spec/flipper/api/v1/actions/feature_spec.rb
spec/flipper/api/v1/actions/features_spec.rb
spec/flipper/api/v1/actions/groups_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_actors_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_time_gate_spec.rb

Adds error documentation to the api v1 README completing #195 
For now the more_info link will link to https://github.com/jnunemaker/flipper/tree/master/docs/api#error-code-reference.  The anchor tags don't work in preview because user-content is prepended to the ids, but will work when merged.
I updated the ErrorResponse initialize function to just take `(code, message, http_status)` and no link to documentation since for now we only have a few error messages and they all live in one place so that instance variable is just set in the initializer.  Maybe in the future we'll change this if we add more info about errors and want to link to more specific sections of the docs
updates specs to account for adding the more_info in the response

Api v1 error docs and response messaging

---

lib/flipper/ui/actions/actors_gate.rb
lib/flipper/ui/actions/features.rb
lib/flipper/ui/actions/groups_gate.rb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb

Fix https://github.com/jnunemaker/flipper/issues/204
By investigating the initial issue, I was able to identify several areas impacted by it.
1. Using the UI to create two features with similar names but different whitespace:
```ruby
> $flipper.features
=> #<Set: {#<Flipper::Feature:70136261075520 name="   whitespace", state=:conditional, enabled_gate_names=[:actor], adapter=:memoizable>,
#<Flipper::Feature:70136261217520 name="   whitespace   ", state=:conditional, enabled_gate_names=[:actor], adapter=:memoizable>}>
```
2. Still via the UI, adding an actor to the second one seemed to have actually added it to the first one.
3. Both links in the UI leads to the same feature:
4. Copy-pasting actor values from one Flipper UI to another adds some whitespace which ends up in Flipper:
```ruby …
```

Strip whitespace out of feature/actor/group values posted by UI

---

docs/DockerCompose.md
lib/flipper/adapters/redis_cache.rb
spec/flipper/adapters/dalli_spec.rb
spec/flipper/adapters/redis_cache_spec.rb
spec/helper.rb
test/adapters/dalli_test.rb
test/adapters/mongo_test.rb
test/adapters/redis_cache_test.rb
test/adapters/redis_test.rb

closes #142 - first attempt at adding a redis cache adapter. I've added some testing setup that was broken and documented running them via docker-compose.
I mimicked the dalli cache adapter almost entirely, i think the only choices i had to make were is this included in the flipper-redis gem and how to use the setex cmd (ttl) with redis. I chose yes and to marshal objects when storing / retrieving, limited testing on this show the features serializing in and out of redis ok.  Happy to change the implementation if you want.
Side note: when testing in the pry debugger, the inspect method on a feature would call the `adapter.get`[here](https://github.com/jnunemaker/flipper/blob/cb7ba8f9bc0c69671978d3f28d212b893b01323b/lib/flipper/feature.rb#L219) and warm the cache which took me a while to …

Add redis cache adapter

---

lib/flipper/adapters/sequel.rb
lib/generators/flipper/templates/sequel_migration.rb

Use primary keys with Sequel, which are usually more practically that simple indexes.
It appears the current implementation does not require a feature to exists when creating a gate, so a foreign key on ``flipper_gates.feature_key`` cannot be used.

Use primary keys with Sequel

---

docs/Adapters.md

* no longer supported so we shouldn't point users there

Remove link to deprecated Rails 4 ActiveRecord  Adapter

---

docs/api/README.md

* mount priority matters.  mount /flipper-api before /flipper
* since mount uses match with anchor: false any route after flipper*
will match that rack application and so flipper-api would never get called

Add mount priority section to Flipper Api docs

---

lib/flipper/api.rb
lib/flipper/api/json_params.rb
spec/flipper/api/json_params_spec.rb
spec/flipper/api/v1/actions/percentage_of_actors_gate_spec.rb

This is an interesting issue uncovered from some work I've been doing on the api client.  RSpec sends post requests as x-www-form-urlencoded and rack adds any parameters to the Rack::Request#params hash.  The api actions look at params for the request data.  The problem is that for application/json requests rack does not add the parsed body to the params hash.  This PR adds simple custom middleware that for request with content-type application/json will parse the body and add the key/values to the params hash so that the api can handle both x-www-form-urlencoded and application/json requests.
I added a spec for the middleware and also to one of the api action specs to ensure the api middleware stack is working as expected.  The middleware spec keeps me confident the middleware works as …

Add JsonParams to Api to add JSON request body to rack params

---

lib/flipper/api.rb
lib/flipper/api/middleware.rb
lib/flipper/api/setup_env.rb
spec/flipper/api/setup_env_spec.rb
spec/flipper/api_spec.rb

This makes it so that the API can use flipper from the request env instead of having to pass an instance in. One benefit is that the middleware is more simple. It now just reads `env["flipper"]`. Another benefit is that the flipper instance can be dynamically determined in upstream middleware. This allows the API to be mounted with a prefix or something and a little bit of middleware that sets the flipper instance based on that prefix.
This is all backwards compatible, it just adds a bit more flexiblity for something I have up my sleeve unrelated to this. 😁 @AlexWheeler any thoughts on this either way?

Api Flipper from Env

---

.rubocop.yml
lib/flipper/api/v1/actions/features.rb
spec/flipper/api/v1/actions/features_spec.rb

This makes it so that by specifying `keys` (comma separated list of keys) parameter to `/features` limits the output to the requested keys. Should make https://github.com/jnunemaker/flipper/pull/221#discussion_r98196015 easy to do.

API Get Multi Support

---

docs/api/README.md
lib/flipper/adapters/http.rb
lib/flipper/api.rb
lib/flipper/api/action.rb
lib/flipper/api/middleware.rb
lib/flipper/api/v1/actions/actors_gate.rb
lib/flipper/api/v1/actions/boolean_gate.rb
lib/flipper/api/v1/actions/feature.rb
lib/flipper/api/v1/actions/features.rb
lib/flipper/api/v1/actions/groups_gate.rb
lib/flipper/api/v1/actions/percentage_of_actors_gate.rb
lib/flipper/api/v1/actions/percentage_of_time_gate.rb
spec/flipper/adapters/http_spec.rb
spec/flipper/api/v1/actions/actors_gate_spec.rb
spec/flipper/api/v1/actions/boolean_gate_spec.rb
spec/flipper/api/v1/actions/feature_spec.rb
spec/flipper/api/v1/actions/features_spec.rb
spec/flipper/api/v1/actions/groups_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_actors_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_time_gate_spec.rb
spec/flipper/api_spec.rb

This shortens the api routes to exactly what is necessary for flipper. This allows for flexibility as people can mount this however/wherever they want (e.g. `/flipper`, `/flipper/api`, `/flipper/api/v1`).
Any downside of doing this that I'm overlooking?

Shorten API Routes

---

.rubocop_todo.yml
docs/Optimization.md
lib/flipper/api.rb
lib/flipper/middleware/memoizer.rb
lib/flipper/middleware/setup_env.rb
lib/flipper/ui.rb
lib/flipper/ui/middleware.rb
spec/flipper/middleware/memoizer_spec.rb
spec/flipper/middleware/setup_env_spec.rb

This makes the UI load from the env. It also makes the memoizer middleware use the flipper from env for consistency sake. The downside is that it requires a parameter change to the memoizer middleware, but it is a minor change we can note it in the changelog for those upgrading.

UI Flipper from Env

---

docs/Optimization.md

completes #231 
*Applications using [Redis](https://redis.io/) via the [redis-rb]* - I think its a good idea to be explicit here in case a project is using a redis client with a different public API, even though clients with the same public api will work this is the one we've tested it against and the official ruby client.
* removes trailing whitespace

Add RedisCache to Optimization.md

---

docs/sequel/README.md

This adds a link to the Sequel library's home page in the flipper-sequel adapter's README page.
If one does not know about the existence of the Sequel library, then it may be ambiguous whether this adapter supports a particular library or just plain-old SQL (as its commonly pronounced "sequel"). This cost me a considerable amount of time spent getting flipper-sequel to work on my ActiveRecord-decoupled Rails app, until I realized later that it was meant for integration with an app that uses the Sequel library.
I hope this helps.

adds link to Sequel library in the Sequel adapter README

---

lib/flipper/adapters/http.rb
lib/flipper/api/v1/actions/percentage_of_actors_gate.rb
lib/flipper/api/v1/actions/percentage_of_time_gate.rb
spec/flipper/api/v1/actions/percentage_of_actors_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_time_gate_spec.rb

decouple the api from the adapter when disabling percentage_of_gate, percentage_of_actor gates
* The disable gate route should only be used to fully disable a gate by always setting the gate value to 0.  This way the enable/disable endpoints don't behave the same.  The enable endpoint is for setting the value to anything other than 0.  The disable endpoint will be used for always setting the value to 0
* The adapter handles which route to request, for percentage_of_time,
percentage_of_actors.  Will request enable with the value when
adapter.disable is passed a value > 0

Api DELETE features/:feature/:gate can only fully disable a gate

---

lib/flipper/adapters/http.rb
lib/flipper/api/v1/actions/feature.rb
lib/flipper/api/v1/actions/features.rb
spec/flipper/api/v1/actions/feature_spec.rb
spec/flipper/api/v1/actions/features_spec.rb

* The HTTP adapter, as opposed to the api will return any features requested that do not exist.  This will not effect how flipper currently works with the http adapter.  It will only change how the api responds.
Right now for `http_adapter.get(flipper[:feature_that_is_not_in_database])` the json response will return json that makes it seem like the resource exists when it really doesn't.  The same applies for get_multi.
This PR changes this so that `/features/:feature_that_does_not_exist` will 404, and the http adapter will handle the returning of the feature so that it still works the same way from the perspective of a flipper.  It will just initialize a new flipper feature.  In other words `flipper[:some_non_existant_feature]` will still return a feature instance.
It also filters the …

Api no longer returns features that do not exist yet - let HTTP adapter handle this

---

docs/api/README.md
lib/flipper/adapters/http.rb
lib/flipper/api/middleware.rb
lib/flipper/api/v1/actions/clear_feature.rb
lib/flipper/feature.rb
spec/flipper/api/v1/actions/clear_feature_spec.rb

* adds clear feature endpoint to api
* uses clear feature endpoint for http adapter `clear`
* changes feature#disable to disable for all gates instead of clearing for boolean and disabling for the rest

Disable/Clear Tweaks

---

lib/flipper.rb
lib/flipper/api/v1/actions/groups_gate.rb
lib/flipper/registry.rb
lib/flipper/ui/actions/groups_gate.rb
spec/flipper/adapters/http_spec.rb
spec/flipper/api/v1/actions/groups_gate_spec.rb
spec/flipper/dsl_spec.rb
spec/flipper/registry_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb
spec/flipper_spec.rb

This makes it possible to enable/disable groups that are not registered. The use case is API's that are mounted on their own apart from where the groups are registered in the code.

Allow Unregistered Groups

---

lib/flipper/gates/percentage_of_actors.rb

`Percentage#open?` has 2 things named key, a method and a local variable that shadows it. This works fine but is confusing to read.
This patch renames the local variable, since `#key` is part of the `Gate` interface.

Rename shadowing variable

---

docker-compose.yml
docs/DockerCompose.md
examples/mongo/basic.rb
examples/mongo/internals.rb
examples/redis/basic.rb
examples/redis/internals.rb
examples/redis/namespaced.rb
spec/flipper/adapters/dalli_spec.rb
spec/flipper/adapters/mongo_spec.rb
spec/flipper/adapters/redis_cache_spec.rb
spec/flipper/adapters/redis_spec.rb
test/adapters/dalli_test.rb
test/adapters/mongo_test.rb
test/adapters/redis_cache_test.rb
test/adapters/redis_test.rb

- fixing typo in docker compose docs
- :fire:-ing boxen remnants
```bash
docker-compose run --rm app bundle exec rspec
docker-compose run --rm app bundle exec test
docker-compose run --rm app bundle exec rubocop -D
```

[minor] Fixing Typo and Removing Boxen Remnants

---

lib/flipper/cloud.rb
spec/flipper/cloud_spec.rb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/boolean_gate_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/actions/gate_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb
spec/flipper/ui/actions/percentage_of_actors_gate_spec.rb
spec/flipper/ui/actions/percentage_of_time_gate_spec.rb
spec/flipper/ui_spec.rb

This makes it possible to pass an instrumenter to the `Flipper.new` call so feature operations can be instrumented. Additionally, it allows passing an adapter wrapper so people can wrap the lower level http adapter with caching, instrumentation, logging or whatever.

Instrumented Cloud

---

.rubocop_todo.yml
docs/Adapters.md
docs/Optimization.md
lib/flipper/adapter.rb
lib/flipper/adapters/http.rb
lib/flipper/adapters/instrumented.rb
lib/flipper/adapters/memoizable.rb
lib/flipper/adapters/operation_logger.rb
lib/flipper/dsl.rb
lib/flipper/middleware/memoizer.rb
lib/flipper/spec/shared_adapter_specs.rb
lib/flipper/test/shared_adapter_test.rb
spec/flipper/adapters/http_spec.rb
spec/flipper/adapters/memoizable_spec.rb
spec/flipper/dsl_spec.rb
spec/flipper/middleware/memoizer_spec.rb
spec/helper.rb

Previously preload_all made to adapter calls -- features and get_multi with result of features. This makes it so an adapter can get all features and gate values in one call instead of two by adding `Adapter#get_all`. The default implementation is a call to features and then to get_multi like before, but now it is possible for adapters to be more efficient and do it all in one call. I added it to Http adapter as an example. I'll open an issue to add it to other adapters.

Adapter#get_all

---

lib/flipper/adapters/http.rb
lib/flipper/adapters/http/client.rb
spec/flipper/adapters/http_spec.rb

addresses #254 
* allow an http adapter user to set where to write debug output by
specifying sink in the configuration hash passed to the adapter
* this will most likely be $stderr/$stdout
* will need to add documentation in next PR

Allow set_debug_output for http adapter via configuration hash

---

docs/http/README.md

fixes #257 
adds debug_output option to http adapter documentation section.  
Decided not to add it to the example code since I think its better to not have someone who is just getting started copy/paste this code with debug_output set.

Add debug_output documentation to http adapter doc.

---

docs/Adapters.md

super minor but thought it would be nice to have these alphabetized (case insensitive because it makes it easier to spot named adapters i.e. Redis v. memory) to make it easier to spot supported adapters

Alphabetize adapters

---

lib/flipper/adapters/cache_store.rb
spec/flipper/adapters/cache_store_spec.rb

#263 
* Helpful adapter for Rails users that want to use their configured cache store cache.
http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html
*  can pass options as described in docs above e.g. :expires_in to Adapters::CacheStore constructor to use this for all flipper keys.  Otherwise it will default to whatever the user has set on the cache via its constructor.
From docs ^ *Some implementations may not support all methods beyond the basic cache methods of fetch, write, read, exist?, and delete.*  Sinc we're using fetch_all we might want to check if the `@cache` responds to fetch_all and if not then call our own fetch_all that loops with fetch.  Thoughts?

Add cache_store adapter for caching via ActiveSupport::CacheStore

---

flipper-cache-store.gemspec

fixes #267 
* Has ActiveSupport runtime dependency
Docs PR up #268

Add Flipper Cache Store .gemspec

---

examples/percentage_of_actors.rb
examples/percentage_of_time.rb
lib/flipper/gate_values.rb
lib/flipper/gates/percentage_of_actors.rb
lib/flipper/typecast.rb
lib/flipper/types/percentage.rb
spec/flipper/dsl_spec.rb
spec/flipper/gates/percentage_of_actors_spec.rb
spec/flipper/gates/percentage_of_time_spec.rb
spec/flipper/typecast_spec.rb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/integration_spec.rb

Would love some eyes on this to make sure I'm doing it right or if there are any downsides with the approach.
closes #273

Support percentages with up to 3 decimals

---

docs/Optimization.md

fixes #277 
I'm thinking we remove the link to the CacheStore docs from the adapters list since we don't list any other cache adapters there. thoughts?

Add CacheStore Optimization docs

---

README.md
examples/basic.rb
examples/configuring_default.rb
lib/flipper.rb
lib/flipper/configuration.rb
lib/flipper/errors.rb
spec/flipper/configuration_spec.rb
spec/flipper_spec.rb
spec/helper.rb

This adds a tidy little spot to configure the default flipper instance. This has long been a thing people have to think about to use flipper. Rarely do people use multiple flipper instances in the same app, and if they want to they still can, but at least now it is wrapped up for most people.
```ruby 
require 'flipper'
require 'flipper/adapters/memory'
Flipper.configure do |config|
config.default { Flipper.new(Flipper::Adapters::Memory.new) }
end
puts Flipper.enabled?(:search)
Flipper.enable(:search)
puts Flipper.enabled?(:search)
Flipper.disable(:search)
```
`default` is configured with a block. This makes it so it can either return a single instance no matter what or generate an instance safe for a thread, if necessary. A top level method `Flipper.instance` exists to memoize an instance …

Default Instance Storage

---

docs/ui/README.md

Reworked the security section in the UI README to add a section on rack basic auth strategy.
The idea came from https://github.com/jnunemaker/flipper/issues/292.

Update UI README with rack basic auth security

---

docs/Optimization.md
docs/cache_store/README.md
flipper-cache_store.gemspec
lib/flipper-cache_store.rb

This matches active_record and ruby idioms in general. Mixing dash and underscore is a bit more ugly but matches [rubygems guidelines](http://guides.rubygems.org/name-your-gem/):
```
net-http-digest_auth	require 'net/http/digest_auth'	Net::HTTP::DigestAuth
```

cache-store => cache_store

---

.rubocop_todo.yml
docs/Adapters.md
docs/Optimization.md
docs/active_support_cache_store/README.md
examples/cloud/cached_in_memory.rb
flipper-active_support_cache_store.gemspec
lib/flipper-active_support_cache_store.rb
lib/flipper-cache_store.rb
lib/flipper/adapters/active_support_cache_store.rb
spec/flipper/adapters/active_support_cache_store_spec.rb

flipper-cache_store is owned by someone else so I can't rename the gem to that as I tried in #295. This fixes that by prefixing it with AS which makes sense any way.

ActiveSupportCacheStore

---

.rubocop.yml
lib/flipper/adapters/active_record.rb
lib/flipper/adapters/active_support_cache_store.rb
lib/flipper/adapters/dalli.rb
lib/flipper/adapters/memoizable.rb
lib/flipper/adapters/memory.rb
lib/flipper/adapters/mongo.rb
lib/flipper/adapters/pstore.rb
lib/flipper/adapters/read_only.rb
lib/flipper/adapters/redis.rb
lib/flipper/adapters/redis_cache.rb
lib/flipper/adapters/sequel.rb
spec/flipper/adapters/active_support_cache_store_spec.rb
spec/flipper/adapters/dalli_spec.rb
spec/flipper/adapters/memoizable_spec.rb
spec/flipper/adapters/redis_cache_spec.rb
spec/flipper/middleware/memoizer_spec.rb

In testing `preload_all` with Flipper::Cloud, I found that the memoizing and caching adapters weren't working correctly with `get_all` (which `preload_all` uses). Several things were subtly not right causing extra net/http calls. I added several specs that verify the number of network calls and tested externally with a few apps I control. This also adds get_all to all the adapters flipper supports out of the box. This ensures that when possible `preload_all` and `get_all` do the fewest network calls. 
There is some funny business with caching and get_all. The trick with get_all and caching is you don't know the features so you can't do a get_multi for all features. This left two obvious options:
1. wrap the entire get_all call with its own cache fetch block.
2. add an extra network call …

All The Get Alls

---

docs/ui/README.md

I'm evaluating flipper (and it's ui) and I've found out this typo while experimenting

Typo in cut and paste instructions for rails

---

lib/flipper/ui/views/add_feature.erb

Fix something that has been grinding my gears, not automatically focusing on the only text input on the page when clicking on _Add Feature_. Now it does:

Autofocus on new feature text input

---

lib/flipper/ui.rb
lib/flipper/ui/configuration.rb
lib/flipper/ui/configuration/option.rb
lib/flipper/ui/views/feature.erb
spec/flipper/ui/configuration_spec.rb
spec/flipper/ui_spec.rb

spike on #63 to allow users to customize the Flipper UI text, curious what everyone thinks.
```
Flipper::UI.configure do |c|
c.percentage_of_actors.title = "% of Actors"
c.percentage_of_actors.description = "percentage of actors rule :)"
c.actors.description = "Enable any actor by entering that actor's flipper_id"
c.delete.title = "DO NOT PRESS!"
c.delete.description = "Who knows what will happen?!"
end
```
results in:
I also played with the idea of making the configuration have a bit cleaner dsl something like. the latter is cleaner, but the above is simpler, would be cool to hear thoughts on this:
```
Flipper::UI.configure do |c|
c.actors do
title ""
description ""
end
end
```

Implement UI::Configuration so users can customize Flipper UI text

---

lib/flipper.rb
spec/flipper_spec.rb

Tiny little doodad to update the Flipper.instance explicitly. Primarily useful for testing where you can just use the memory adapter like:
```ruby
Flipper.instance = Flipper.new(Flipper::Adapters::Memory.new)
```

Add Flipper.instance writer method

---

lib/flipper.rb
lib/flipper/api/v1/actions/clear_feature.rb
lib/flipper/api/v1/actions/features.rb
lib/flipper/dsl.rb
lib/flipper/feature.rb
lib/flipper/middleware/memoizer.rb
lib/flipper/ui/actions/feature.rb
lib/flipper/ui/actions/features.rb
lib/flipper/ui/configuration.rb
spec/flipper/dsl_spec.rb
spec/flipper/feature_spec.rb
spec/flipper/middleware/memoizer_spec.rb
spec/flipper/ui/configuration_spec.rb
spec/flipper_spec.rb

This delegates `#memoize=` and `#memoizing?` on `Flipper::DSL` and `Flipper` which makes it so we don't have to reach for Flipper.adapter in order to use these in the memoizer middleware, which feels better. I also snagged other places we were doing flipper.adapter.whatever and used methods that already existed (e.g. `add` and `remove`) or added what was necessary (e.g. `clear`) to `Flipper::Feature` to avoid it. Nothing big, just feels a little better.

Avoid Reaching into Adapter

---

Rakefile

* shared tests live under test so this task can be removed

Remove rake task that no longer is necessary

---

.rubocop.yml
lib/flipper/adapters/active_record.rb
lib/flipper/adapters/sequel.rb
lib/flipper/spec/shared_adapter_specs.rb
lib/flipper/test/shared_adapter_test.rb

As reported in https://github.com/jnunemaker/flipper/issues/296#issuecomment-339997906:
> One issue I had to work around was that double-enabling a feature for an actor or group threw a Postgres exception for violating the index_flipper_gates_on_feature_key_and_key_and_value unique constraint on the gates table. So I've got an enable_once wrapper that does a check-and-set to avoid the exception in the initializer that sets up basic rules and the rake tasks that perform administration.
This fixes that for Active Record and Sequel by adding shared adapter tests and swallowing the unique errors. I think this is fine as enabling something that is already enabled should return the same result as enabling it the first time.

Fix double enable of actor/group unique error

---

.codeclimate.yml

* Code Climate is analyzing files under lib/flipper/ui/public/ which is
mostly vendored js/css giving us an F!

Remove ui/public/ from code climate results

---

spec/flipper/adapter_spec.rb

* the feature was enabled using source flipper, but wasn't being asserted that the feature
was properly imported to the destination flipper

Adds assertion for importing boolean enabled features

---

flipper-redis.gemspec

As [redis-rb 4.0.1](https://github.com/redis/redis-rb/releases/tag/v4.0.1) is now released, why don't allow to use it with flipper-redis adapter?

Allow to use redis-adapter with redis 4.0.x

---

flipper-rollout.gemspec
lib/flipper/adapters/rollout.rb
spec/flipper/adapters/rollout_spec.rb

Addresses #308 
Adds an adapter to import Rollout data into Flipper
Rollout supports the equivalent to Flipper's
* groups
* actors
* percentage_of_actors
* boolean (sort of...via 100% percentage enabled)
Rollout does not support
* percentage_of_time
Importing only requires `features`, `get` to be implemented.
Questions/Notes:
* for the methods the adapter doesn't implement I'm thinking of raising an error similar to the read only adapter to make it clear that this adapter is only for importing since rollout doesn't have feature parity
* I'm testing ["can have one feature imported"`](https://github.com/jnunemaker/flipper/compare/rollout-adapter?expand=1#diff-ce5ff96d129103e0d6d194b6be39790dR59) type stuff where its not really testing the rollout adapter its really testing adapter.import, …

Rollout Adapter for importing rollout data into Flipper

---

lib/flipper/adapters/redis_cache.rb
spec/flipper/adapters/redis_cache_spec.rb

Problem described in https://github.com/jnunemaker/flipper/issues/323#issuecomment-355622010.
* added spec to show that it failed to cache for the intended cache key
* added code change to use the correct cache key

Redis Cache Key Fix

---

lib/flipper/ui.rb
lib/flipper/ui/actions/feature.rb
lib/flipper/ui/views/feature.erb
lib/flipper/ui/views/feature_removal_disabled.erb
spec/flipper/ui/actions/feature_spec.rb

This change allows the `Danger Zone` + `Delete Feature` button to be removed from the Flipper UI.
I thought it was a good idea do have it, because sometimes adding or removing features is a job for developers only, who might want to do it only via console, rake tasks, migrations or seeds.
What do you guys think?

Allow feature removal from the UI to be disabled

---

lib/flipper/adapters/active_record.rb
lib/flipper/adapters/sequel.rb
lib/flipper/spec/shared_adapter_specs.rb
lib/flipper/test/shared_adapter_test.rb
spec/flipper/adapters/active_record_spec.rb

Fixes the sequel and active record adapters to include even disabled features in get_all. The issue was using an inner join between feature and gate tables, which means features in the feature table but not in the gate table (because they were fully disabled) were not represented in get_all. 
fixes https://github.com/jnunemaker/flipper/issues/324

Active Record get_all Fix

---

docs/rollout/README.md
examples/rollout/basic.rb
examples/rollout/import.rb
lib/flipper/adapters/rollout.rb
spec/flipper/adapters/rollout_spec.rb

* Adds require for flipper/errors since `AdapterMethodNotSupportedError` inherits from Flipper::Error defined in that file.
* Ensures rollout works fine for features that do not exist. In some basic scripts I was playing with this was causing problems.
* Makes rollout percentage 100 equal to flipper fully enabled. Rollout doesn't clear other gate values (users/groups) when fully enabled and uses percentage == 100 as fully enabled instead of a different key (like boolean: false in flipper). Flipper.enabled?(:foo) returns false for 100% of actors enabled because no actor was passed, but rollout returns true (as it has no other way to denote 100% of actors enabled vs enabled regardless of actor). Making rollout 100% == flipper fully enabled means that rollout.active?(:chat) and …

Rollout tweaks

---

.rubocop.yml
Gemfile
Guardfile

If using guard, this makes it automatically show rubocop problems and fixes some for you. Makes it easier to keep formatting up to date.

Guard Rubocop

---

lib/flipper/adapters/sync.rb
lib/flipper/adapters/sync/interval_synchronizer.rb
lib/flipper/cloud/configuration.rb
spec/flipper/cloud/configuration_spec.rb
spec/flipper/cloud_spec.rb

This uses the sync adapter for cloud. It allows people to set a local adapter to keep in sync with remote. The default is in memory which is similar to using the active support in memory caching that we were recommending for cloud. The primary difference is that this is resilient to cloud being unavailable because exceptions are rescued and the local is persisted across restarts (assuming you are using active record, redis, mongo, or whatever instead of the default memory adapter). It also persists longer because the in memory cache expires, but this does not.

Cloud Sync

---

Changelog.md
examples/cloud/local_adapter.rb
lib/flipper/adapters/sync.rb
lib/flipper/adapters/sync/interval_synchronizer.rb
lib/flipper/cloud/configuration.rb
spec/flipper/adapters/sync/interval_synchronizer_spec.rb
spec/flipper/cloud/configuration_spec.rb

No reason we can't use floats to represent milliseconds (e.g. 0.1 for 100ms). Smaller numbers are easier to deal with and every other number is seconds so having one in milliseconds is confusing.

Change sync_interval to seconds

---

lib/flipper/errors.rb
lib/flipper/ui.rb
lib/flipper/ui/action.rb
lib/flipper/ui/actions/add_feature.rb
lib/flipper/ui/actions/feature.rb
lib/flipper/ui/actions/features.rb
lib/flipper/ui/configuration.rb
lib/flipper/ui/views/feature.erb
lib/flipper/ui/views/feature_creation_disabled.erb
lib/flipper/ui/views/feature_removal_disabled.erb
lib/flipper/ui/views/layout.erb
spec/flipper/ui/actions/add_feature_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/configuration_spec.rb
spec/flipper/ui_spec.rb

Resolves: https://github.com/jnunemaker/flipper/issues/326
Alex had the idea of linking to the docs to let the user know how to update the configuration, but I wasn't really sure what that would look like. I just mentioned in the exception that the configuration options moved to `Flipper::UI::Configure` which might be enough?
Now that Flipper::UI::Configuration exists, some configuration options on Flipper::UI should be moved over.
- Moved attribute_breadcrumb_href, feature_creation_enabled, and feature_removal_enabled from Flipper::UI to Flipper::UI::Configuration
- Deprecate the values on Flipper::UI by raising an exception

Move Flipper::UI configuration options to Flipper::UI::Configuration

---

lib/flipper/cloud/configuration.rb
spec/flipper/cloud/configuration_spec.rb
spec/flipper/cloud_spec.rb

No biggie. I got tired of talking about Flipper Cloud and linking to featureflipper.com so I went for the io. Now they match.

Switch to flippercloud.io for cloud domain

---

lib/flipper/ui/middleware.rb
spec/flipper/api/v1/actions/feature_spec.rb
spec/flipper/ui/actions/feature_spec.rb

Because of the order of the action classes, the features index route was picked. I put it last so now the feature actions will get picked prior to the list.
Fixes #352

Allow feature names to end with "features" in UI

---

lib/flipper/ui/views/feature.erb

Before this change, enabling a feature for 100% of actors or time would hide the "Enable" action for the Boolean Gate. After this change, the boolean gate actions can be used independently of the current value of the other gates.
A feature being enabled for 100% actors is not necessarily the same as enabling it for "everyone", depending on how you configure your actors. In a typical scenario, users are actors. Enabling a feature for 100% actors would enable it for 100% *logged in* users. But `Flipper.enabled?(:my_feature)` would return false for logged out users.

Reveal real boolean value for feature in UI

---

flipper-active_record.gemspec
flipper-active_support_cache_store.gemspec
flipper-api.gemspec
flipper-cloud.gemspec
flipper-dalli.gemspec
flipper-mongo.gemspec
flipper-redis.gemspec
flipper-rollout.gemspec
flipper-sequel.gemspec
flipper-ui.gemspec
flipper.gemspec
lib/flipper/metadata.rb

* gemspecs accept metadata for displaying links on RubyGems. This adds
a link to the changelog so RubyGems users can easily link to flipper's
changelog.
*would appear in links section*
We could add a reference to this in say `module Flipper` (similar to `Flipper::VERSION`) and then add this to every adapter's .gemspec too. what do ya think?

Add changelog url to flipper.gemspec metadata

---

flipper-moneta.gemspec
lib/flipper/adapters/moneta.rb
spec/flipper/adapters/moneta_spec.rb

Adds Moneta adapter #307 
This is an improved PR over #330, where we're now optimizing for reads. Moneta has a Logging middleware that I used with a [simple script to log database accesses](https://gist.github.com/AlexWheeler/0a6562f3805db6c00e7931993a664017) and below are the results:
#330  (previous PR)
```
############### 3x enable(:feature) #####################
Moneta load("features") -> nil
Moneta store("features", #<Set: {"feature"}>) -> #<Set: {"feature"}>
Moneta load("feature/feature/actors") -> nil
Moneta store("feature/feature/actors", #<Set: {"1"}>) -> #<Set: {"1"}>
Moneta load("features") -> #<Set: {"feature"}>
Moneta store("features", #<Set: {"feature"}>) -> #<Set: {"feature"}>
Moneta load("feature/feature/actors") -> #<Set: {"1"}>
Moneta store("feature/feature/actors", …
```

Moneta adapter each feature as key

---

lib/flipper/feature.rb
spec/flipper/api/v1/actions/feature_spec.rb
spec/flipper/api/v1/actions/features_spec.rb

Groups are likely the least performant gate since the others just do equality and inclusion checks. Groups could do other network calls or what not, so let's just re-order them to have groups gate last.
xref https://github.com/jnunemaker/flipper/issues/369

Re-order gates for improved performance (in some cases)

---

lib/flipper/middleware/memoizer.rb

This file is now required in the main flipper file. That makes it more convenient to use, but there are some projects that don't use rack. Having this require means that even though they don't use this, they need rack so the require won't fail. 
I see two choices. 
1. Make memoizer a separate gem with a rack dependency and a require.
2. Remove the require as this does which effectively only requires the dependency if you use this file. This makes it more like it was before when it was a separate require but avoids the separate require. If the code is executed in a request, rack is required for rack request and body proxy. If it is not used in a request it is not required. Should be fine.
fixes #373

Remove require of rack body proxy

---

lib/flipper/api/action.rb
lib/flipper/ui/action.rb

* Before we supported slashes we [unescaped the feature name](https://github.com/jnunemaker/flipper/pull/362/files#diff-57d52309df29e6c236372b6f6c88fabeL36), but the
change to get feature_name using  `FeatureNameFromRoute` is not
unescaping feature names. 
This causes 2 issues:
1.  The redirect when creating the feature displays the feature name unescaped
2.  When you go to enable a gate for the feature the feature_key is the unescaped value
Reproduce:
* Flipper, Flipper UI, Flipper ActiveRecord - (all 0.16.0)
* Rails 4.2.4
* browsers: ChromeVersion 69.0.3497.100 and SafariVersion 11.1
1.  Navigate to `features/new` and create `my_team:cool_feature`.  This will redirect you to feature page:
2.  Confirm database feature record looks correct
3.  Enable the boolean gate for this feature by …

Unescapes feature_name in FeatureNameFromRoute

---

spec/flipper/ui/action_spec.rb

@jnunemaker great idea about [adding a regression test](https://github.com/jnunemaker/flipper/pull/377) lemme know what ya think
* 7151715c6afd55b3b87b46aada152dff3fc13ea9 was merged which escapes
feature_names like we were doing before the change to support slashes
and adding the FeatureNameFromRoute module for pulling the feature name
out of the request.  This adds a regression spec to make sure this
continues to work in the future as changes are made.
* I decided to test this in a separate describe block since the current `action_subclass` is super simple and really easy to understand what its testing.  Since the `FeatureNameFromRoute` returns a request body with values and includes a module, etc I think its nice to separate the two.  Since `feature_name` is a private method I didn't …

Add regression test for escaping feature names

---

lib/flipper/ui/views/feature.erb

It seems that in the `feature` view of `Flipper::UI`, a couple of the bootstrap responsive utility classes are off-by-one on the breakpoints they target. Changing `md` to `sm` in two places and `md` to `lg` in one place seems to fix the issues without introducing unwanted side effects (from what I can tell.
Before:
After:
Before:
After:

Target correct bootstrap breakpoints in Flipper::UI feature view

---

.rubocop.yml
.travis.yml
flipper-sequel.gemspec

I want to use this gem, but we are heavy-users of Sequel, and limiting the version to < 5 will block us...
I removed it, and apparently nothing (rspec and rubocop) broke.

Remove version constraint for Sequel gem

---

flipper-redis.gemspec

Redis gem v4.1 was recently released, so any app running it will
cause bundler to resolve to using an older version of `flipper-redis`.
We should consider relaxing the constraint to anything less than v5.
Addresses https://github.com/jnunemaker/flipper/issues/392

Update Redis dependency constraint to < 5

---

flipper-rollout.gemspec

This also bumps the redis dependency for flipper-rollout so it can be used with the latest redis.

Bump redis dep for flipper-rollout

---

lib/flipper/types/group.rb
spec/flipper/types/group_spec.rb

@jnunemaker @supersam654 I went ahead and took a shot at fixing the the issue in #405. See if this makes sense.
When a shorthand block was used when initializing a Group, an error would be thrown about not passing the correct number of arguments. That was due to the arity of the shortand being -1 instead of 1. By taking the absolute value of the arity, an arity of -1 will still correctly set the single_argument instance variable.

Allow shorthand block notation on group types

---

lib/flipper/adapters/instrumented.rb
spec/flipper/adapters/instrumented_spec.rb

When subscribing to notifications it can be useful to know the value of the gate being enabled/disabled. For example, that way you could set up notifications and output the name of the group or the percentage being changed.
This adds a new `thing_value` attribute to the payload of `Instrumented#enable` and `Instrumented#disable`.
Thanks for the great gem!

Include thing_value in payload of Instrumented#enable and #disable

---

flipper-ui.gemspec
lib/flipper/ui/action.rb

Following up on https://github.com/jnunemaker/flipper/pull/397.
This should make `flipper-ui` Rails 5.2 compatible.

Replace Erubis with Erubi (2)

---

lib/flipper/ui.rb

This PR allows to customize `Rack::Protection` middleware list.
Currently we are forced to use `Rack::Protection` defaults, when we may want to use or skip some of them: https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection.rb#L23-L51.

Allow to customize Rack::Protection middleware list

---

lib/flipper-active_record.rb

Per @mike101 in #432:
> I'm not sure if it's just me, but this change seems to have broken Rails for me using Rails 6 and the latest version of this gem with this PR included. I get an error now where bundler is trying to load the gem, and I get an error that it can't find activesupport/lazy_load_hooks.
I typo'd my PR, and forgot the underscore in `active_record`.  I don't know how the tests passed, but they did.  I have manually verified this fix, and would encourage reviewers to do the same.

Fix typo in lib/flipper-active_record.rb

---

spec/flipper/adapters/active_record_requires_spec.rb

This will guard against regressions like that fixed in #437.
I manually validated that this spec generates an error prior to the fix in #437, and runs successfully after.

Add spec testing require of flipper-active_record.rb

---

lib/flipper/ui/views/features.erb

**Motivation**
At the first time I saw the features in the Flipper-ui, I was a little confused about the colors of the squirrel, and when my partner saw it, he tried to click on the squirrel. So I had a simple ideia to put a data-toggle with the feature state name.
**Solution**
It looks like this:

Add data-toggle in squirrel state (flipper-ui) 💅

---

lib/flipper/adapters/redis_cache.rb
spec/flipper/adapters/redis_cache_spec.rb

I've noticed running flipper locally that if you try the following:
```ruby
client = Redis.new(url: redis_url)
old_adapter = Flipper::Adapters::Redis.new(client)
ar_adapter = Flipper::Adapters::ActiveRecord.new
adapter = Flipper::Adapters::RedisCache.new(ar_adapter, client, 3_600)
adapter.import(old_adapter)
```
you get the following error:
```ruby
/usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:126:in `call': ERR wrong number of arguments for 'mget' command (Redis::CommandError)
from /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:930:in `block in mget'
from /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
from /usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
from /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
from …
```

Avoid errors on import when there are no features

---

flipper-cloud.gemspec
flipper-sequel.gemspec
flipper-ui.gemspec
flipper.gemspec
lib/flipper/adapters/redis_cache.rb
lib/flipper/spec/shared_adapter_specs.rb
lib/flipper/test/shared_adapter_test.rb
spec/flipper/adapters/redis_cache_spec.rb

Following up on #441, this makes the test run for every adapter to ensure others do not suffer from the same problem now or in the future.

Shared Specs/Tests for Get All With No Features

---

lib/flipper/adapters/active_record.rb

While in my particular case I'm confused as to why this error even happened, considering the `unless @feature_class.where(key: feature.key).first` check, but, nonetheless, there a typo in which exception to `rescue`... FIXED!

::ActiveRecord::RecordNotUnique > ActiveRecord::RecordNotUnique

---

docs/Gates.md

The documentation doesn't make it clear that the `actor`'s class when checking a group isn't the same as the the class of the actor used in the arguments. 
This change is a small documentation to help clear up that misconception.

Describe actor in Flipper.register

---

lib/flipper/adapters/redis.rb

multi fails on a cluster set.
Fix #451
See https://github.com/jnunemaker/flipper/issues/450#issuecomment-561702603

Remove multi on the Redis adapter for removing a feature

---

docs/ui/README.md

You need to target `Flipper` here as in the example no instance has been assigned to the `flipper` variable.
Just a small change that I ran into when referencing the examples here and trying to load a file.

📝 Update docs for mounting Flipper::UI

---

docs/Adapters.md

Tiny doc update for you. I noticed rails 6 is mentioned elsewhere, just not here.

Update docs: Include Rails 6 in list of versions

---

Dockerfile

Hello folks!
Ive found issues with Ruby versions while setting up my Development environment following Docker instructions from here:
`Docker Compose for contributors`
https://github.com/jnunemaker/flipper/blob/master/docs/DockerCompose.md
```ruby
flipper % docker-compose build
...
OK
flipper % docker-compose run --rm app bundle install
Starting flipper_mongo ... done
Starting flipper_redis ... done
Starting flipper_bundle_cache ... done
Starting flipper_memcached    ... done
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
i18n-1.8.2 requires ruby version >= 2.3.0, which is incompatible with the current version, ruby 2.2.5p319
```
After …

Development with Docker - Ruby version adjusted to avoid gem issues

---

docs/ui/README.md
lib/flipper/ui/action.rb
lib/flipper/ui/actions/feature.rb
lib/flipper/ui/actions/features.rb
lib/flipper/ui/configuration.rb
lib/flipper/ui/decorators/feature.rb
lib/flipper/ui/views/feature.erb
lib/flipper/ui/views/features.erb
spec/flipper/ui/configuration_spec.rb
spec/flipper/ui/decorators/feature_spec.rb
spec/support/descriptions.yml

1. Simple way to provide insights/details about a specific feature within `Flipper::UI`.
2. Avoids generating `feature` keys too long when developers/admins/users need more **context** about a feature's behaviour:
- What is it meant to do ?
- What is it not meant to do ?
- Which sections of the platform it applies to ?
- How it differentiates itself from similar features ?
- What user roles does it apply to ?
- Etc.

Add `descriptions` support for `features`

---

docs/active_record/README.md

This pull request adds some additional context to the `active_record/README.md` for those looking to follow the general conventions on initialising Flipper. This is something that caught my team out in our continuous integration pipeline, so hopefully this is helpful to others that might be following the same pattern.

Updated active_record/README.md with Rails initialization guidance

---

Changelog.md
lib/flipper/feature.rb
spec/flipper/feature_spec.rb

The tldr is that 100% of actors could still return false if the actor doesn't include traffic from users that are not signed in. It would be true for 100% of sessions where session was the actor but not for 100% of users where users may be signed in or signed out. Signed out user would be nil and would return false for enabled.
closes #463

100% of actors now considered conditional rollout

---

lib/flipper/ui/actions/features.rb
lib/flipper/ui/configuration.rb
lib/flipper/ui/views/features.erb
spec/flipper/ui/configuration_spec.rb

This adds a configuration option to display feature descriptions on the 'features' page. Closes https://github.com/jnunemaker/flipper/issues/477.
The recent UI redesign cleaned things up nicely, but having the option to trade a bit of the simplify for the ability more easily find/understand features at-a-glance would be great too.

Add config option for displaying descriptions on features page

---

spec/flipper/adapters/active_support_cache_store_spec.rb
spec/flipper/adapters/dalli_spec.rb
spec/flipper/middleware/memoizer_spec.rb

Most specs relying on Memcached are failing when run in the docker environment. 
This was happening because the Dalli clients used weren't being passed a server URL, and were defaulting to `127.0.0.1:11211`. That works when running the specs in a typical local environment because memcached is usually exposed at that IP/port. But docker exposes it elsewhere!

Get specs passing in docker

---

flipper-ui.gemspec

In https://github.com/jnunemaker/flipper/pull/156 rack-protection was set to >= 1.5.3 and < 2.1.0, which was because it no longer worked with `session["_csrf_token"]`, but did work with `session[:csrf]` in both 1.5.3 and 2.0.0.beta2. Hoping to update it now that that beta changes are live, as this allows installation of flipper alongside the current version of rack-protection.

Bump rack-protection version to < 2.2

---

docs/Optimization.md

This updates the documentation for Optimization to use `Rails.configuration.middleware` instead of `config.middleware`, which makes this a bit more copy/paste ready for new users. As the first comment suggests the code is in `config/initializers/flipper.rb`, the code as described doesn't work. Updating as `Rails.configuration.middleware` makes it ready to go.

Use Rails.configuration instead of config in documentation

---

lib/flipper/api/v1/actions/percentage_of_actors_gate.rb
lib/flipper/api/v1/actions/percentage_of_time_gate.rb
spec/flipper/api/v1/actions/percentage_of_actors_gate_spec.rb
spec/flipper/api/v1/actions/percentage_of_time_gate_spec.rb

The current implementation of percentage actors and time gates allows only integer values.
In [this commit](https://github.com/danielvidal/flipper/commit/82f3b960e127cdebb5e951b14ac04308ea7ddd64) the `Typecast` class started to deal with percentages and I didn't find a reason to not allow the gates to work with decimal values.
cc/ @jnunemaker

Allow actors and time gates to deal with decimal percentages

---

docs/Gates.md

This updates the gates docs to use the "@jnunemaker Approved®" syntax.

Docs: use preferred syntax for gates

---

README.md
examples/basic.rb
examples/cloud/import.rb
examples/dsl.rb
examples/enabled_for_actor.rb
examples/group.rb
examples/group_dynamic_lookup.rb
examples/group_with_members.rb
examples/individual_actor.rb
examples/percentage_of_actors.rb
examples/percentage_of_actors_enabled_check.rb
examples/percentage_of_actors_group.rb
examples/percentage_of_time.rb
lib/flipper/configuration.rb
lib/flipper/errors.rb
spec/flipper/configuration_spec.rb
spec/flipper/middleware/setup_env_spec.rb

This updates the configuration to default to the `Memory` adapter. This allows  the docs and usage examples to be simplified so the first step isn't always "choose an adapter".
This is related to #500 for improving the onboarding experience.

Default to using Memory adapter

---

examples/ui/basic.ru
lib/flipper/ui/configuration.rb
lib/flipper/ui/views/features.erb
lib/flipper/ui/views/layout.erb
spec/flipper/ui/configuration_spec.rb

Just want to help get the word out so people know it exists. This seemed like an easy and unobtrusive way to help. Also it gets that sweet logo in the UI. 😄 
And now you all know I've switched to hey for email due to the pinned tab. 😆 
Can be disabled with:
```ruby
Flipper::UI.configure do |config|
config.cloud_recommendation = false
end
```

Add cloud recommendation to UI

---

README.md
docs/Adapters.md

This is a WIP for some onboarding improvements that I talked about with @jnunemaker.  The goal is to remove as much friction in the onboarding process as possible by clarifying some of the documentation and setting sensible defaults.
Some of these I'll probably work on in separate PRs, but here's what's on my mind so far:

Onboarding improvements

---

.github/workflows/ci.yml
spec/flipper/adapters/active_support_cache_store_spec.rb
spec/flipper/adapters/dalli_spec.rb
spec/flipper/adapters/mongo_spec.rb
spec/flipper/adapters/redis_cache_spec.rb
spec/flipper/adapters/redis_spec.rb
spec/flipper/adapters/rollout_spec.rb
spec/flipper/middleware/memoizer_spec.rb
test/adapters/dalli_test.rb
test/adapters/mongo_test.rb
test/adapters/redis_cache_test.rb
test/adapters/redis_test.rb
test/test_helper.rb

My soul can't handle having failing tests locally. This skips the tests that depend on local services if they fail to connect.

Skip adapter tests if connection fails

---

.github/workflows/ci.yml
spec/flipper/adapters/active_record_spec.rb
spec/flipper/adapters/mongo_spec.rb
spec/flipper/adapters/redis_spec.rb
spec/flipper/adapters/sequel_spec.rb
spec/support/spec_helpers.rb

#502 introduced a failure when running specs in different order. This sets `config.order = :random` in rspec to hopefully expose issues like this sooner.
It also updates GitHub Actions to not run on `push` unless to master.

Randomize order of specs

---

examples/cloud/app.ru
lib/flipper/cloud/configuration.rb
spec/flipper/cloud/configuration_spec.rb
spec/flipper/cloud/dsl_spec.rb
spec/flipper/cloud/middleware_spec.rb
spec/flipper_spec.rb

`sync_secret` always needs to be set if this is changed, so I don't see a need for both settings.
This change was extracted from #506 to try to reduce the scope of that PR.

Deprecate superflous sync_method setting

---

docs/Gates.md

The [default implementation][1] of `Flipper::Identifier` uses a semicolon (instead of a colon) to separate class and id.
[1]: https://github.com/jnunemaker/flipper/blob/f4a50467a6da84f4d886b8bec1df56127446002b/lib/flipper/identifier.rb#L14

docs: fix Flipper::Identifier.flipper_id example

---

docs/Gates.md

I was going through this to write some internal documentation, and I think the `percentage_of_time` documentation has a small bug.
Calling `Flipper.enable_percentage_of_time 5` results in 
```
ArgumentError: wrong number of arguments (given 1, expected 2)
```

Gates.md: update Percentage of Time documentation

---

lib/flipper/adapters/redis_cache.rb

The [signature of `Redis#mget` actually requires a splatted array of keys to fetch](https://www.rubydoc.info/gems/redis/3.1.0/Redis%3Amget). Currently, the implementation works fine for the default `redis` gem, but the current behavior (non-spreading) does not work with `redis-store`. This patch should fix that.

Spread cache keys when using `Redis#mget`

---

README.md

I found a typo when trying to install the gem, especially when installing the flipper with an active record adapter. So this PR is just to fix the typo :)

Fix small typo in README.md in installing flipper-active_record part.

---

lib/flipper/cloud/routes.rb
spec/flipper/cloud/engine_spec.rb

`Cloud.app` takes the flipper instance as the first argument. Unfortunately, the tests didn't expose the mis-configuration.
This updates the tests to make a real request to the webhook app to ensure it is configured properly.

Fix configuration of Cloud webhook app

---

lib/flipper/middleware/memoizer.rb
spec/flipper/middleware/memoizer_spec.rb

When upgrading to the next release of flipper, anyone using the Memoizer middleware will need to make some changes. Specifically, they will need to either remove the mounting of the middleware and update the `preload` config, if they are using it…
```diff
- Rails.application.middleware.use Flipper::Middleware::Memoizer, preload: [:some, :features]
+ Rails.application.configure do
+  config.flipper.preload = [:some, :features]
+ end
```
…or disable memoizing from the Railtie:
```diff
+ Rails.application.configure do
+  config.flipper.memoize = false
+ end
```
This pull request updates the Memoizer middleware to be a noop if `flipper.memoizing?` is already true.  This should allow for the first instance of the middleware (manually mounted in `config/initializers/*`) to continue working, and …

Only perform memoization and preloading once

---

Changelog.md
lib/flipper/adapters/active_support_cache_store.rb
lib/flipper/spec/shared_adapter_specs.rb
spec/flipper/adapters/active_support_cache_store_spec.rb

The current approach with caching adapters does something like this:
1. On write, delete the entry from the cache.
2. On the next read, repopulate the cache.
Unfortunately this can be subject to subtle race conditions if the
underlying storage (in our case, a replicated database) gives a stale
read for item 2 - which may be in a different process / thread / host
entirely. More details on our specific case are available at
https://gitlab.com/gitlab-org/gitlab/-/issues/325452.
The new `write_through` option to the ActiveSupportCacheStore adapter's
initialiser allows the user to opt in to write-through caching, where
the new value is immediately written to the cache in step 1.

Add `write_through` to ActiveSupport cache adapter

---

.gitignore
Guardfile
examples/api/basic.ru
examples/api/custom_memoized.ru
examples/api/memoized.ru
examples/ui/authorization.ru
examples/ui/basic.ru
lib/flipper/api.rb
lib/flipper/api/middleware.rb
lib/flipper/middleware/memoizer.rb
lib/flipper/ui.rb
lib/flipper/ui/middleware.rb
spec/flipper/api_spec.rb
spec/flipper/ui_spec.rb

Default rails and flipper setups will use memoizer so having ui include it causes the double memoize warning message, which can be confusing.
This removes the memoizer from UI and adds the backwards compatibility stuff we need to make it all work the same.
We can add a doc on how to add your own memoizer for just the ui:
```ruby
run Flipper::UI.app { |builder|
builder.use Flipper::Middleware::SetupEnv, some_flipper, env_key: "some_flipper"
builder.use Flipper::Middleware::Memoizer, env_key: "some_flipper"
}
```
We can also add a doc on how to add your own memoizer for just the api: 
```ruby
run Flipper::Api.app { |builder|
builder.use Flipper::Middleware::SetupEnv, api_flipper, env_key: "api_flipper"
builder.use Flipper::Middleware::Memoizer, env_key: "api_flipper"
}
```
I'm open to doing …

Remove memoizer from UI

---

lib/flipper/railtie.rb

Requires `flipper/instrumentation/log_subscriber` in the Railtie unless logging is explicitly disabled. The log subscriber already does a check for `logger.debug?`, so I think it makes sense to require this regardless of environment.

Enable log subscriber by default in Rails

---

Gemfile
lib/flipper/adapters/active_record.rb
lib/flipper/adapters/sequel.rb

Arel and Sequel know how to handle reserved words in terms of escape characters for the given underlying database technology. This way we don't have to assume that DB-specific knowledge.
Closes #535

fix(active-record): arelize get_all query

---

lib/flipper/ui/action.rb
lib/flipper/ui/actions/actors_gate.rb
lib/flipper/ui/actions/features.rb
lib/flipper/ui/actions/groups_gate.rb
lib/flipper/ui/actions/percentage_of_actors_gate.rb
lib/flipper/ui/actions/percentage_of_time_gate.rb
spec/flipper/api/v1/actions/actors_gate_spec.rb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/boolean_gate_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb
spec/flipper/ui/actions/percentage_of_actors_gate_spec.rb
spec/flipper/ui/actions/percentage_of_time_gate_spec.rb

Before it would cause browser errors when you enabled or disabled in any way.
Now it will work properly. I don't know if this is the best or right way but it works so I'm shipping it.
closes #496

Handle spaces in names gracefully in UI

---

.github/workflows/ci.yml

Just remembered we lost the rails matrix tests when switching to GitHub Actions. Got the supported versions back in. Technically I relaxed the constraint to >= 4.2 rails but that is YMMV.

Matrix Rails

---

docker-compose.yml
lib/flipper/ui/action.rb
lib/flipper/ui/views/layout.erb

Should fix #538.
Only the first commit (3686e8ae33ec47eac2b9e24f02c84ffd40e2dfff) is strictly necessary - the next one (6009d1534a63f5f9feba257f0672c16176d14fcb) tries to remove the duplicated source urls between the CSP & the layout template, but I don't know that the extra indirection is worth it - see what you think.
I was getting fun errors testing this in docker-compose on an M1 mac (eg Mongo failing with `runtime: failed to create new OS thread`) so updated that too.

Add a Content-Security-Policy

---

lib/flipper/adapters/sync/synchronizer.rb

Checking if `feature_key` is in the `local_get_all` hash before attempting to access it prevents unintended modification of the `local_get_all` hash which occurs when `@local` is an ActiveRecord adapter.
Issue: [#553](https://github.com/jnunemaker/flipper/issues/553)

Fix Synchronizer issue that occurs for ActiveRecord adapter

---

lib/flipper/ui/views/feature.erb

It seems that when the octicons were removed this was left over. The remove button isn't visible at the moment (it's clickable even if it's invisible)

Fix remove button for groups

---

lib/flipper/railtie.rb

The railtie was using `after: : load_config_initializers` to ensure app initializers were run before mounting the middleware. As described in #562, this appears to cause the middleware stack to be initialized prematurely and changing the order of middleware. That option is not needed here and was only added to be explicit because we have another initializer that is `before: :load_config_initializers`. Looking closer at the [rails booting process](https://api.rubyonrails.org/classes/Rails/Application.html#class-Rails::Application-label-Booting+process), initializers from railties run after `config/initializers`.
Fixes #562

Fix railtie initialization to avoid altering middleware order

---

flipper-ui.gemspec
lib/flipper/ui/action.rb
lib/flipper/ui/views/feature.erb
lib/flipper/ui/views/features.erb
lib/flipper/ui/views/layout.erb

Hi!
I was looking for a way to format the banner / descriptions a little bit more, but it's a bit tricky since Flipper UI is Rack middleware. Would you be open to something like this where HTML is allowed to render in the ERBs?
There _shouldn't_ be any user-inputted text here since this would all come from config values, but also happy to make it an option (possibly that just changes the `escape` option passed to Erubi) if that's preferred.
Thanks!

feat: allow HTML in banner and feature descriptions

---

.github/workflows/examples.yml

All PRs from external contributors currently have failing tests due to FLIPPER_CLOUD_TOKEN not being available. This skips the examples if secrets are not available.
Most externals contributions don't impact examples. If we do get a major contribution, we can just run the examples manually.

Avoid running examples if secrets not available

---

lib/flipper/adapters/pstore.rb
spec/flipper/adapters/pstore_spec.rb

not sure the thread_safe attribute is working.  should we save the value, extract it out of @store via `.instance_variable_get`, or delete the accessor since it may not be needed?  (I also sorted the variables to keep things tidy)

pstore thread_safe fix

---

lib/flipper/adapters/sync/interval_synchronizer.rb
spec/flipper/adapters/sync/interval_synchronizer_spec.rb

it seems like `Synchronizer.now` is only needed for testing.  can we de-duplicate this with the instance method?

synchronizer now

---

spec/flipper/instrumenters/noop_spec.rb

use rspec's `expect {}.to yield_control` syntax to ensure block is being called
https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/yield-matchers

noop spec cleanup

---

lib/flipper/instrumenters/memory.rb
spec/flipper/instrumenters/memory_spec.rb

upgrade memory instrumentor to capture exceptions raised, similar to `ActiveSupport::Notifications`: https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activesupport/lib/active_support/notifications/instrumenter.rb#L25

memory instrumenter

---

Changelog.md
lib/flipper/adapters/failover.rb
spec/flipper/adapters/failover_spec.rb

create an adapter which fails back to a secondary adapter during read operations if a io / network type errors occurs

failover adapter

---

lib/flipper/adapters/http/error.rb
spec/flipper/adapters/http_spec.rb

The API returns nice error messages but our errors weren't showing them.
Now we are showing them. Much easier to figure out what went wrong and fix it on your own.

Improve http error message

---

.github/workflows/ci.yml
flipper-active_record.gemspec

Rails 7.0 was just released and having the dependency `< 7` prevents us from installing flipper with a new rails app.
I'm not sure _what_ needs to change or why the restriction on `< 7` so opening the easiest PR for this, but let me know if there are things that worry you and I'll work on them!
One thing that might hold this back is that Rails 7 requires Ruby 2.7.0+ and I see tests with ruby 2.5 and 2.6.

Support ActiveRecord 7.0

---

lib/flipper/ui/action.rb

Signed-off-by: Marcus Heng <marcushwz@gmail.com>
Hi, first of all thank you so much for this gem, I love using it at work! Today, one of my team member report that Flipper UI is taking some time to load. I gave it a look and were able to reproduce it on my local. After diving into it, the problem seems to cause by the `Bootstrap JS CDN`. Attached are images of both Chrome and Firefox refusing to load the `4.0 version`
- Chrome
- Firefox
- Upgraded Bootstrap JS to v4.6 (Fixed both Chrome and Firefox refusing to load v4.0)
- Upgraded jquery to `jquery-3.6.0` (This isn't causing any problem, but I think it might be good to update to the latest stable)
- Chrome
- Firefox
PS: Sorry about the code formatting, let me know if you want to change back the formatting. Those were done by local dev …

Upgrade bootstrap js and jquery

---

Changelog.md
lib/flipper/railtie.rb
spec/flipper/railtie_spec.rb

After #563, Flipper configuration in `config/initializers/*` is ignored because the Memoization middleware gets mounted before initializers are run. This reverts 713e9d1 and fixes the specs to expose this issue.
The tests pass here, but it's going to cause issues that #563 was meant to fix, so I need some help.
I've been spelunking on Rails initialization process all day, and I can't quite figure out the order of initializers. Some initializers run after `load_config_initializers` without declaring a `before`/`after` dependency (see all of `action_view` below), while most run earlier in the process.
* Running `flipper.memoizer` before `build_middleware_stack` initializer, but that appears to be defined on a `Finalizer` module outside of the app's initializers, so you can't order anything …

Fix railtie initialization to mount middleware after config/intializers/*

---

.github/workflows/ci.yml
.github/workflows/examples.yml
lib/flipper/types/group.rb

This PR adds Ruby 3.0 and 3.1 to the CI matrix.
Aside from the configuration changes in ci.yml it:
1. Changes the setup-ruby action to the currently supported action
2. Updates examples.yml to include Rails 7.0.0 and the necessary matrix exclusions
3. Changes Flipper::Types::Group so that it properly parses parameters for procs in Ruby 3.0 and up
As an aside, even though there's an `if` clause in the `examples.yml` that disables in on forked repos, I did run it and ensure it was green before submitting this PR.

Add Ruby 3.0 and 3.1 to the CI matrix

---

flipper-redis.gemspec
lib/flipper/adapters/redis.rb

Context: https://github.com/redis/redis-rb/pull/1059
The following is deprecated
```ruby
redis.pipelined do
redis.get(key)
end
```
And should be rewritten as:
```ruby
redis.pipelined do |pipeline|
pipeline.get(key)
end
```
Functionally it makes no difference.
This API is available since Redis 3.0.

Fix deprecated uses of `Redis#pipelined`

---

Changelog.md
lib/flipper/ui.rb

If we return a `Rack::Builder` instance, it will call `to_app` for every request. That's not performant, but more importantly, it makes apps that want to use `Rack::Session::Pool` not work. `Rack::Session::Pool` uses `@pool` to store the sessions; if we rebuild the Rack application for every request, it can't keep track of sessions because it resets the variable.
The following application wouldn't work without this change:
```ruby
require "rack"
require "flipper"
require "flipper-ui"
flipper = Flipper.new(Flipper::Adapters::Memory.new)
run Rack::URLMap.new({
"/flipper" => Flipper::UI.app(flipper) do |builder|
builder.use Rack::Session::Pool
end
})
```

Call to_app before returning the rack app

---

lib/flipper/actor.rb
spec/flipper/actor_spec.rb

This allows them to be used as hash-keys - eg
```ruby
features = {
Flipper::Actor.new("abc") => [:foo, :bar],
Flipper::Actor.new("def") => [:baz],
}
features[Flipper::Actor.new("abc")] #=> [:foo, :bar]
```

Add Flipper::Actor#hash

---

flipper-ui.gemspec
lib/flipper/api.rb
lib/flipper/cloud.rb
lib/flipper/ui.rb
spec/flipper/api_spec.rb
spec/flipper/cloud/middleware_spec.rb
spec/flipper/ui_spec.rb

`rails routes` use to have pretty output. Then we added `to_app` on the builder call in https://github.com/jnunemaker/flipper/pull/606, which was good but broke the output. 
This fixes the output and changes the spec to ensure we don't break in the future. 
Additionally, I added the performance improvement in https://github.com/jnunemaker/flipper/pull/606 to the API and Cloud apps and ensured there output is correct.
Lastly, I bumped the rack-protection dependency version up to make it so 2.2 works as well. This should fix the problem in #617.
closes #614 
closes #617

Pretty Up `rails routes` again

---

lib/flipper/types/actor.rb

`kwargs` are not supported for ruby 3.0 for `method_missing`
`method_missing` is called in blocks of flippers groups when calling method of `actor`
(https://www.flippercloud.io/docs/features#enablement-group)

Add kwargs for method_missing using ruby 3.0

---

lib/flipper/adapters/failsafe.rb
spec/flipper/adapters/failsafe_spec.rb

Create an adapter that fails safe, ie. closed, when issues arise.  This protects against issues like network hiccups or Redis crashes from taking down an application using Flipper.

failsafe adapter

---

lib/flipper/adapters/active_record.rb

Alternative approach to #628 to ease connecting to alternate database. This defines an abstract base class for Flipper's internal ActiveRecord models, which can be used to configure connection handling and probably other options. It also switches from using `ActiveRecord::Base` to the internal `Feature` class (or the `feature_class` option passed when the adapter is initialized) to get a new connection.
This allows configuring connection options:
```ruby
Flipper::Adapters::ActiveRecord::Model.connects_to database: {
writing: :flipper, reading: :flipper_replica
}
```
cc @ceritium

ActiveRecord: base class for internal models

---

lib/flipper/middleware/memoizer.rb
spec/flipper/middleware/memoizer_spec.rb

Rack::BodyProxy allows deferring execution until after the response has sent to the client. It's intended for expensive cleanup (after the response is rendered, but before it's sent) that could delay delivering the response to the client. Cleaning up memoization is not an expensive operation, and I suspect this use of BodyProxy is the source for warnings in https://github.com/jnunemaker/flipper/issues/604.
I haven't studied it closely, but my guess is that after this middleware returns the rendered response body, puma (or possibly  any threaded web server) delivers the response to the client in another thread, returning execution of the app thread to Rails to start the next request. If the next request starts before the previous one is finished sending, then the next request will produce …

Remove use of Rack::BodyProxy

---

examples/instrumentation.rb
examples/instrumentation_last_accessed_at.rb

Running the instrumentation examples I experienced `uninitialized constant ActiveSupport::IsolatedExecutionState (NameError)`
This PR adds the specific require statement, resolving the error.

Fixes examples/instrumentation* NameError

---

Changelog.md
flipper-redis.gemspec
lib/flipper/adapters/redis.rb
spec/flipper/adapters/redis_spec.rb

closes https://github.com/jnunemaker/flipper/issues/659

Flipper fails with Redis >= 4.8.0

---

lib/flipper/ui/configuration.rb
lib/flipper/ui/public/js/application.js
lib/flipper/ui/views/feature.erb

Added Confirm Warning when fully enabling a feature

Added Confirm Warning for Fully Enable feature

---

flipper-redis.gemspec

Fixes https://github.com/jnunemaker/flipper/issues/666.
I have deployed this branch to production using `redis` gem version 5.0.5 and it works for me.

Relax redis constraint in flipper-redis.gemspec from `< 5` to `< 6`

---

lib/flipper/adapters/redis.rb

Because the client might not be a `::Redis` instance, for example it could be a [`MockRedis` ](https://github.com/sds/mock_redis/) instance

Check sadd_returns_boolean on the actual client class rather than `::Redis`

---

lib/flipper/adapters/poll/poller.rb

Fixes these webmock warnings in the specs by stopping any pollers when resetting.
```
000000010aa163e0 /Users/bkeepers/projects/flipper/lib/flipper/adapters/poll/poller.rb:105 run> terminated with exception (report_on_exception is true):
/Users/bkeepers/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.14.0/lib/webmock/http_lib_adapters/net_http.rb:114:in `request': Real HTTP connections are disabled. Unregistered request: GET https://www.flippercloud.io/adapter/features with headers {'Accept'=>'application/json', 'Client-Engine'=>'ruby', 'Client-Hostname'=>'Brandons-MacBook-Air.local', 'Client-Language'=>'ruby', 'Client-Language-Version'=>'3.1.2 p20 (2022-04-12)', 'Client-Pid'=>'20281', 'Client-Platform'=>'arm64-darwin21', 'Client-Thread'=>'44440', …
```

Stop poller instances when resetting

---

lib/flipper/ui/public/js/application.js
lib/flipper/ui/views/feature.erb
spec/flipper/ui/configuration_spec.rb

I noticed that the confirmation text set up by `confirm_fully_enable` does not work correctly if `feature_removal_enabled` was set to `false`.
This was due to the node with ID `feature_name` only being present within the form included when `feature_removal_enabled` was set to true. This lead to a situation where your UI would display "undefined" as the prompt text though when that or the actual feature name was used the  flag was not toggled since it was comparing the string "undefined" to an undefined variable.
This commit fixes this edge case by decoupling the confirmation text for both buttons from the `feature_removal_enabled` form and moving them into data attributes on the button being clicked. This allows them to be enabled/disabled separately without impacting each other. The …

Flipper UI - Fix issue preventing feature flags being enabled when confirm_fully_enable is on and feature_removal_enabled is off

---

flipper.gemspec

This PR cleans up two small things in the gemspec:
- Drop reference to non-existent bin/ directory
- Drop Travis reference

Remove executables directive, this gem has 0 exe

---

.github/workflows/ci.yml
.github/workflows/examples.yml

This PR tries to use `bundler-cache: true`, and in order to do that, moves around some instructions.

CI: Use bundler-cache: true to simplify the installation parts

---

lib/flipper/adapters/memory.rb
lib/flipper/adapters/poll/poller.rb
spec/flipper/adapters/memory_spec.rb
spec/flipper/adapters/poll/poller_spec.rb

Addresses https://github.com/jnunemaker/flipper/pull/699#discussion_r1126465923
~~This uses `Concurrent::Hash` (which just uses `Hash` on MRI since any C function is thread safe and Hash is implemented in C) as the backend source for the memory adapter and replaces any non-threadsafe uses (like `||=`).~~
See [update](https://github.com/jnunemaker/flipper/pull/702#issuecomment-1462629962)

Make Memory adapter threadsafe

---

lib/flipper/adapters/active_record.rb
spec/flipper/adapters/active_record_spec.rb

[ConnectionPool#with_connection](https://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#method-i-with_connection) ensures the connection from the thread pool is checked back in if it wasn't already reserved for this thread. So using this adapter in a background thread won't permanently hold onto a connection that is infrequently used.
In a thread that already has an established connection (like web process) it will just reuse the connection.
cc @jhuber

ActiveRecord adapter: wrap all reads/writes in `with_connection`

---

Gemfile
benchmark/enabled_ips.rb
benchmark/enabled_profile.rb
benchmark/instrumentation_ips.rb
benchmark/typecast_ips.rb
lib/flipper/feature.rb
lib/flipper/feature_check_context.rb
lib/flipper/gate_values.rb
lib/flipper/gates/actor.rb
lib/flipper/gates/boolean.rb
lib/flipper/gates/group.rb
lib/flipper/gates/percentage_of_actors.rb
lib/flipper/gates/percentage_of_time.rb
lib/flipper/typecast.rb
spec/flipper/adapters/rollout_spec.rb
spec/flipper/feature_check_context_spec.rb
spec/flipper/gate_values_spec.rb
spec/flipper/gates/percentage_of_actors_spec.rb
spec/flipper/typecast_spec.rb

@bkeepers and I paired on some Flipper#enabled? performance. 
When we started:
```
with actor    164.802k (± 0.6%) i/s -    832.116k in   5.049373s
without actor    259.654k (± 0.3%) i/s -      1.307M in   5.034628s
```
When we finished:
```
with actor    255.295k (± 0.9%) i/s -      1.300M in   5.092099s
without actor    356.474k (± 0.9%) i/s -      1.787M in   5.013634s
```
~55% for with actor. ~37% without an actor.

Improve `Flipper#enabled?` Performance

---

spec/flipper/adapters/dalli_spec.rb
spec/flipper/adapters/mongo_spec.rb
spec/flipper/adapters/redis_cache_spec.rb
spec/flipper/adapters/redis_spec.rb
spec/flipper/adapters/rollout_spec.rb
spec/support/skippable.rb

Minor tweak to speed up skipping of adapter specs in local dev if underlying sever is not available. Currently each example has to wait for the error, which could be ~1 second per example. This sets a global and just short-circuits the skip if one of the pervious examples in the example group fail.
Before:
```
Finished in 50.18 seconds (files took 5.08 seconds to load)
1719 examples, 0 failures, 69 pending
```
After:
```
Finished in 10.86 seconds (files took 2.63 seconds to load)
1719 examples, 0 failures, 69 pending
```

Speed up skipped adapter specs

---

lib/flipper/adapters/active_record.rb

It's `enable`, not `disable`.
💚

Fix typo in code comment

---

lib/flipper/expressions/duration.rb
lib/flipper/expressions/now.rb
lib/flipper/expressions/time.rb
spec/flipper/expressions/duration_spec.rb
spec/flipper/expressions/now_spec.rb
spec/flipper/expressions/time_spec.rb

Enable a feature at a specific time:
```js
{
"GreaterThan": [
{ "Now": [] },
{ "Time": "2023-03-26 13:00:00Z" }
]
}
```
Give an actor a 14 day trial:
```js
{
"LessThan": [
{ "Property": ["created_at"] },
{
"Plus": [
{ "Now": [] },
{ "Duration": [14, "days"] }
]
}
]
}
```
> Note: `Plus` isn't implemented yet, but it's on my list

Add Time, Now, and Duration expression types

---

lib/flipper/instrumentation/log_subscriber.rb

This fixes a performance degradation introduced in https://github.com/jnunemaker/flipper/pull/726
Move runtime version comparison into file-load comparison, since the gem version does not change while the process is running.
This removes two Gem::Version.new allocations (which in turn does some regex scans and string allocations), as well as a Hash allocation (`{ bold: true }` on Rails 7.1+) per `color_name` call.

Improve performance of `color_name` function in log subscriber

---

Changelog.md
examples/ui/prefixed.ru
lib/flipper/ui/views/layout.erb
lib/flipper/version.rb

Fixes #741, which was introduced in #731. I also added `examples/ui/prefixed.ru`, which is a rack app we can use to test this in the future.

UI: fix path to bundled assets when mapped to a prefix

---

lib/flipper/cloud/configuration.rb
spec/flipper/cloud/configuration_spec.rb
spec/flipper/cloud_spec.rb

The goal is for sync to trust the remote and overwrite local with remote. 
The problem is that using dual write adapter for poll adapter in cloud means that a sync could write back to remote (cloud). If we use local adapter for poll then a sync can only affect local and never touch remote. 
Then we can use dual write with poll adapter as the read and cloud as the remote to ensure that local Flipper.enable calls (and similar) will still go to both local and write.

Avoid any possibility of sync writing back to remote

---

Changelog.md
examples/dsl.rb
lib/flipper.rb
lib/flipper/dsl.rb
lib/flipper/spec/shared_adapter_specs.rb
lib/flipper/test/shared_adapter_test.rb
spec/flipper/adapters/active_support_cache_store_spec.rb
spec/flipper/adapters/dual_write_spec.rb
spec/flipper/adapters/instrumented_spec.rb
spec/flipper/adapters/memoizable_spec.rb
spec/flipper/adapters/operation_logger_spec.rb
spec/flipper/adapters/read_only_spec.rb
spec/flipper/api/v1/actions/clear_feature_spec.rb
spec/flipper/dsl_spec.rb
spec/flipper_integration_spec.rb
spec/flipper_spec.rb
spec/spec_helper.rb

Backported from #692 to the v1.0 branch

Remove convenience methods on `Flipper` and `Flipper::DSL`

---

.github/workflows/examples.yml
Changelog.md
flipper-active_record.gemspec
flipper-active_support_cache_store.gemspec
flipper-api.gemspec
flipper-cloud.gemspec
flipper-dalli.gemspec
flipper-moneta.gemspec
flipper-mongo.gemspec
flipper-redis.gemspec
flipper-rollout.gemspec
flipper-sequel.gemspec
flipper-ui.gemspec
flipper.gemspec
lib/flipper/adapters/active_record.rb
lib/flipper/adapters/sequel.rb
lib/flipper/metadata.rb
lib/flipper/middleware/memoizer.rb
lib/flipper/ui/views/features.erb
spec/flipper/ui_spec.rb

This repo has moved from @jnunemaker's beloved personal account to the new @flippercloud account, where all things Flipper are being consolidated.

Update links to new GitHub org

---

lib/flipper/api.rb
lib/flipper/api/action.rb
spec/flipper/api/action_spec.rb
spec/flipper/api_spec.rb

@bkeepers @garrettdimon any downside to doing it this way? I mostly just want to make `curl -Is` work with api requests.

Allow head requests to api

---

lib/flipper/adapter.rb
lib/flipper/adapters/active_record.rb
lib/flipper/adapters/active_support_cache_store.rb
lib/flipper/adapters/dalli.rb
lib/flipper/adapters/dual_write.rb
lib/flipper/adapters/failover.rb
lib/flipper/adapters/failsafe.rb
lib/flipper/adapters/http.rb
lib/flipper/adapters/instrumented.rb
lib/flipper/adapters/memoizable.rb
lib/flipper/adapters/memory.rb
lib/flipper/adapters/moneta.rb
lib/flipper/adapters/mongo.rb
lib/flipper/adapters/operation_logger.rb
lib/flipper/adapters/poll.rb
lib/flipper/adapters/pstore.rb
lib/flipper/adapters/read_only.rb
lib/flipper/adapters/redis.rb
lib/flipper/adapters/redis_cache.rb
lib/flipper/adapters/rollout.rb
lib/flipper/adapters/sequel.rb
lib/flipper/adapters/sync.rb

I noticed while working on #760 that every adapter defines `#name` and it's just a variable set in initialize. This PR added a default `Adapter#name` method, which is just the `snake_case` version of the `ClassName`.
In https://github.com/flippercloud/flipper/pull/760#discussion_r1328013132, @jnunemaker said:
> I don't usually allow changing the adapter name. But seeing it makes me wonder if we should allow this for people as I could see scenarios where someone wants to override for instrumentation purposes.
Currently, the ActiveRecord and Sequel adapters are the only ones that allow setting the name. Those will still work with this change. Should we allow others?

Define default Adapter#name

---

lib/flipper/model/active_record.rb
spec/flipper/engine_spec.rb
spec/flipper/model/active_record_spec.rb

Given this model:
```ruby
class MyEngine::User < User
end
```
Flipper currently considers these two different actors:
```ruby
User.first.flipper_id # => "User;1"
MyEngine::User.first.flipper_id # => "MyEngine::User;1"
```
This PR uses ActiveRecord's `base_class` method, which returns the first non-abstract class in the class hierarchy, as the class to use in the `#flipper_id` method.
```ruby
MyEngine::User.first.flipper_id # => "User;1"
```
Fixes #757

Use base_class to determine flipper_id for ActiveRecord actors

---

lib/flipper/ui/actions/feature.rb
lib/flipper/ui/configuration.rb
lib/flipper/ui/decorators/feature.rb
lib/flipper/ui/views/feature.erb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/configuration_spec.rb
spec/support/actor_names.yml

This makes actor names more readable. Made sure there were no N+1 queries like @jnunemaker suggested!
I also wrote a deserializer to convert actor identifiers to ActiveRecord fields:
```ruby
def self.humanize_identifiers(keys, field)
grouped_keys = {}
actor_names = {}
keys.each do |key|
parts = key.split(";")
grouped_keys[parts.first] ||= []
grouped_keys[parts.first] << parts.second
end
grouped_keys.each do |model, ids|
model.constantize.where(id: ids).find_each do |resource|
actor_names["#{resource.class.name};#{resource.id}"] = resource.send(field)
end
end
actor_names
end
```
I'm not sure how that can fit in the project, apart from adding it to the README. Suggestions appreciated.

Human readable actor names

---

lib/flipper/ui/actions/file.rb

When using Rack >= 3.0.0 you get this error message on boot an app with Flipper UI :
```
warning: Rack::File is deprecated and will be removed in Rack 3.1
```
This PR detects if `Rack::Files` is available and tries to use it instead.
Closes https://github.com/flippercloud/flipper/issues/769
[Rack deprecation source](https://github.com/rack/rack/pull/1720)

Handle deprecation of Rack::File in Rack 3.1

---

lib/flipper/adapter.rb
lib/flipper/adapters/memoizable.rb
lib/flipper/adapters/read_only.rb
lib/flipper/dsl.rb
lib/flipper/ui/action.rb
lib/flipper/ui/actions/actors_gate.rb
lib/flipper/ui/actions/add_feature.rb
lib/flipper/ui/actions/boolean_gate.rb
lib/flipper/ui/actions/feature.rb
lib/flipper/ui/actions/features.rb
lib/flipper/ui/actions/groups_gate.rb
lib/flipper/ui/actions/percentage_of_actors_gate.rb
lib/flipper/ui/actions/percentage_of_time_gate.rb
lib/flipper/ui/views/feature.erb
lib/flipper/ui/views/features.erb
lib/flipper/ui/views/read_only.erb
spec/flipper/adapters/read_only_spec.rb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/add_feature_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb

We have a particular business-critical application that uses Flipper flags, and we would like to provide a completely read-only UI with Flipper. I know of a way to do this, which is to set `Flipper::UI`'s configuration to be read only. However, this same application is a bit a "nexus" for some smaller apps, and therefore we have multiple instances of `Flipper::UI` at play here. The different instances each control the flipper flags for the different applications. 
I was able to see that there's a `ReadOnly` adapter however:
```
readonly_app = Flipper::UI.app(Flipper.new(Flipper::Adapters::ReadOnly.new(connection)))
```
But this doesn't hide all the UI buttons in Flipper UI. Here's what I see in that app by default:
Having all the buttons and forms present makes our security people …

Hide UI elements when Flipper is in read-only mode

---

lib/flipper/adapters/http/client.rb
spec/flipper/adapters/http_spec.rb
spec/flipper/cloud/telemetry/submitter_spec.rb

Sends Rails, Sinatra, and Hanami versions so we can prioritize which versions to support.
cc #776

Include client framework versions in API requests

---

lib/flipper/configuration.rb
spec/flipper/configuration_spec.rb
spec/flipper/instrumentation/statsd_subscriber_spec.rb
spec/spec_helper.rb

following up on our discussion in https://github.com/flippercloud/flipper/pull/778 to enable
```ruby
Flipper.configure do |conf|
conf.statsd = my_client
end
```
this would simplify statsd integration and abstract away the subscriber logic.  I don't love the embedded requires and have an idea to rework that if we'd like.  we may want to put `ActiveSupport::Notifications.subscribe` into a method and pair it with a way to unsubscribe, so that it can be done multiple times (especially for testing)

statsd config

---

Changelog.md
lib/flipper/engine.rb
spec/flipper/engine_spec.rb

This allows setting Flipper Cloud secrets via [Rails credentials](https://edgeguides.rubyonrails.org/security.html#custom-credentials)
```
$ rails credentials:edit
```
```
flipper:
cloud_token: <your-cloud-token>
cloud_sync_secret: <your-webhook-secret>
```

Load Cloud secrets from Rails credentials

---

lib/flipper/adapters/active_record.rb
spec/flipper/adapters/active_record_spec.rb

This only happens when you haven't migrated yet likely. 
xref https://github.com/flippercloud/flipper/issues/557#issuecomment-1850350022

Fix AR adapter when table doesn't exist

---

Changelog.md
lib/flipper/adapters/active_record.rb
lib/generators/flipper/templates/migration.erb
lib/generators/flipper/templates/update/migrations/01_create_flipper_tables.rb.erb
lib/generators/flipper/templates/update/migrations/02_change_flipper_gates_value_to_text.rb.erb
lib/generators/flipper/update_generator.rb
test_rails/generators/flipper/active_record_generator_test.rb
test_rails/generators/flipper/update_generator_test.rb
test_rails/helper.rb

```
❯ rails generate flipper:update
identical  db/migrate/20231211183256_create_flipper_tables.rb
create  db/migrate/20231211183315_change_flipper_gates_value_to_text.rb
❯ rake db:migrate
== 20231211183315 ChangeFlipperGatesValueToText: migrating ====================
-- change_column(:flipper_gates, :value, :text)
-> 0.0046s
== 20231211183315 ChangeFlipperGatesValueToText: migrated (0.0051s) ===========
```

Add `rails generate flipper:update` to generate migrations for updates

---

flipper.gemspec
lib/flipper/engine.rb
lib/flipper/ui/action.rb
lib/flipper/ui/public/js/version.js
lib/flipper/ui/views/layout.erb
lib/flipper/version.rb

This PR adds badges to notify of new Flipper releases along with Ruby/Rails version deprecations (#776). Here is worst case scenario where a user has deprecated Ruby/Rails versions, and an old Flipper version.

UI: show a badges for new releases and deprecations

---

lib/flipper/engine.rb

Flipper fails to load due to missing method `default_strict_value`
```
/Users/user/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/railtie.rb:228:in `method_missing': undefined local variable or method `default_strict_value' for Flipper::Engine:Class (NameError)
from /Users/user/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.1.2/lib/flipper/engine.rb:13:in `block in <class:Engine>'
```
Moving the method to the top of the class (before it's used) solves the problem.
Tested on a brand new rails project
Rails 7.1.2
Ruby 3.2.2
Gemfile:
```
gem "flipper", "~> 1.1", require: false
gem "flipper-redis", require: false
gem "flipper-ui", require: false
```
flipper initializer:
```
require "flipper"
require "flipper/adapters/redis"
require …
```

Fix: Define default_strict_value before it's called

---

Guardfile
lib/flipper/adapters/http/client.rb
lib/flipper/cloud/configuration.rb
lib/flipper/cloud/middleware.rb
lib/flipper/cloud/telemetry/submitter.rb
spec/flipper/adapters/http/client_spec.rb
spec/flipper/adapters/http_spec.rb
spec/flipper/cloud/configuration_spec.rb
spec/flipper/cloud/dsl_spec.rb
spec/flipper/cloud/middleware_spec.rb
spec/flipper/cloud/telemetry/submitter_spec.rb
spec/flipper/cloud/telemetry_spec.rb
spec/flipper/cloud_spec.rb
spec/flipper/engine_spec.rb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/boolean_gate_spec.rb
spec/flipper/ui/actions/export_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb
spec/flipper/ui/actions/home_spec.rb
spec/flipper/ui/actions/import_spec.rb
spec/flipper/ui/actions/percentage_of_actors_gate_spec.rb
spec/flipper/ui/actions/percentage_of_time_gate_spec.rb
spec/flipper/ui_spec.rb
spec/flipper_spec.rb

I get confused about headers in ruby all the time: is it suppose to be capitalized, lower case, a symbol or a string, dashes, etc...? 
This standardizes on lower case with dash like rack 3. I also added good job and sidekiq to the detected frameworks in cloud and a way to print http debug_output to stdout via env var (FLIPPER_CLOUD_DEBUG_OUTPUT_STDOUT=true, easier to config than manual).

Standardize Headers

---

.github/workflows/ci.yml
.github/workflows/examples.yml
flipper.gemspec

Only one small change needed for loading `*.gemspec` when building the gem, but previously released gems should work.

Add Ruby 3.3 to build matrix

---

lib/flipper/adapters/sequel.rb

xref https://github.com/flippercloud/flipper/issues/800

Use top level sequel to qualify table and column name

---

flipper.gemspec
lib/flipper/cli.rb
spec/flipper/cli_spec.rb

1. Sets `bindir` in gemspec so ruby gems can find the `flipper` command
2. Delays requiring `flipper` so Rails integration gets properly loaded
3. Format and colorize output
4. Add support for expressions

CLI improvements to output and environment loading

---

lib/generators/flipper/setup_generator.rb
test_rails/generators/flipper/setup_generator_test.rb

```
$ bundle add flipper-active_record
$ rails generate flipper:setup -t <YOUR-TOKEN>
create  db/migrate/20231230170601_create_flipper_tables.rb
append  config/credentials.yml.enc
```

Setup generator

---

examples/ui/basic.ru
lib/flipper/ui/views/feature.erb
spec/flipper/ui/actions/feature_spec.rb

Solves issue - https://github.com/flippercloud/flipper/issues/805
As pointed out in the issue, there is currently an inconsistency between how we treat on the UI some elements (eg. `Flipper::UI.configuration.banner_text`, `@feature.description`) and how we treat the `@feature.actor_names`.
The real world use case is making the actor names clickable as links to the resources that are the actors.
I've done the simplest possible change, not changing anything about the content itself.
- apply `Sanitize.fragment` to the `"#{@feature.actor_names[item]} (#{item})"` on `feature.erb`

Use Sanitize on actor_names

---

Rakefile
lib/flipper/instrumentation/log_subscriber.rb
spec/flipper/adapters/active_record_spec.rb
spec/flipper/adapters/sequel_spec.rb
spec/flipper/instrumentation/log_subscriber_spec.rb
spec/support/spec_helpers.rb
test/adapters/active_record_test.rb

1. Switches to default rspec/minitest dots instead of `documentation` format
2. Silences stdout/stderr on specific tests
Now the test output is clean and it's easier to read errors and deprecation warnings.
```
$ bundle exec rake
Run options: include {:focus=>true}
All examples were filtered out; ignoring {:focus=>true}
Randomized with seed 45888
................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```

Quiet test output to make it easier to find errors

---

Gemfile
lib/flipper/engine.rb
lib/flipper/test_help.rb
spec/flipper/engine_spec.rb
spec/spec_helper.rb
test_rails/system/test_help_test.rb

This adds `flipper/test_help` to automatically configure Rails/RSpec the way [we recommend in our testing docs](https://www.flippercloud.io/docs/testing).
Open questions:
1. Should `Flipper::Engine` automatically require this if `RAILS_ENV=test`? I think yes, but maybe we wait until 2.0 to do that?
2. As brought up in #807, what should the default value for `strict` be in test? Currently with `strict = :warn`, you also have to call `Flipper.add` for each feature. In theory, I like the explicitness of this. It will guard against typos in flag names, but also seems like busywork.  One option is to establish a pattern for defining features in an initializer, like this:
```ruby
module Feature
Hubspot = Flipper.add(:hubspot)
Seo = Flipper.add(:seo)
end
def perform(resource)
return unless …
```

Add flipper/test_help to automatically configure Flipper in tests/specs.

---

lib/flipper/ui/configuration.rb
lib/flipper/ui/public/js/application.js
lib/flipper/ui/views/feature.erb

Similar to https://github.com/flippercloud/flipper/pull/665, this PR adds a confirmation dialog when disabling a flipper. The dialog is configurable with `confirm_disable`.

Add confirmation dialog before disabling a flipper

---

lib/flipper/engine.rb
spec/flipper/engine_spec.rb

Until we come up with a recommended way of declaring features, @jnunemaker and I talked and decided it's best to just disable the strict adapter in tests for now. It will still `:warn` in development, and those that want it can explicitly enable it in test, but the default is just too noisy at the moment.
cc #807

Disable strict in tests for now

---

lib/flipper/test_help.rb

When Rails commands such as db:migrate are executed (formerly rake tasks), they load the broader set of rake tasks, and that means that RSpec's rake task is loaded **without all of the RSpec context**.
This means there _is_ an RSpec constant (from lib/rspec/core/rake_task.rb in rspec-core), but it does not have the configure method. This causes the commands to fail because Flipper's presuming `configure` will always be there if `RSpec` is defined:
```
NoMethodError: undefined method `configure' for RSpec:Module (NoMethodError)
RSpec.configure do |config|
^^^^^^^^^^
/Users/pat/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/test_help.rb:20:in `<main>'
```
I considered loading `rspec/core` here instead to ensure the method exists, but that feels counter to …

Check existence of RSpec.configure for test helpers

---

lib/flipper/test_help.rb

As mentioned in https://github.com/flippercloud/flipper/pull/808#discussion_r1452290722, the current RSpec integration does not clear the state of the adapter between specs. This is being obscured in our test suite at the moment because of how we manually clear `Flipper.configuration = nil`.
For now the fix is just to reconfigure Flipper before each example, which will create a new Memory adapter for each test (which is what it does with Rails+minitest).

Ensure Rspec uses new memory adapter for each example

---

lib/flipper/test_help.rb
test_rails/system/test_help_test.rb

This should fix #821 and fix #822.
I can't get a failing RSpec spec in this repo right now, but will work on refactoring our test suite to get one similar to `test_rails/system/test_help_test.rb` for rspec.
@danielmorrison @norman @rnestler @davidwessman @fcheung can you test this branch and confirm that it works for you?
cc #808

TestHelp: Fix setup for RSpec, clear adapter before each test

---

flipper-ui.gemspec
lib/flipper/api/json_params.rb
lib/flipper/api/v1/actions/import.rb
spec/flipper/adapters/http_spec.rb
spec/support/spec_helpers.rb

Add support for Rack 3. 
Flipper UI's dependency on`rack-protection` was locking the `rack` version to 2x. Now that `rack-protection` 4 is out, we can update `rack`. This brings up a good question: should Flipper UI require `rack-protection`? I like it and all, but might not be Flipper's responsibility. 🤷 
`rack-session` has been extracted from `rack`, but has versions to work under rack 2 or 3.
I have a couple import-related tests failing locally, but haven't figured out exactly why yet. The `request.body` isn't coming through (the body is a `Rackup::Handler::WEBrick::Input` and `.rewind` rails, but trying to `.read` returns `""`).

Support Rack 3

---

spec/flipper/adapters/active_record_spec.rb
spec/flipper/engine_spec.rb
spec/support/fail_on_output.rb
spec/support/fail_on_stdout.rb

#811 cleaned up most of the noise, but there was still a few stray warnings. This updates the specs to fail if there is any output to stdout/stderr if `ENV["CI"]` or `ENV["FAIL_ON_OUTPUT"]` are set, and fixies the remaining warnings.

Fail specs if any output

---

lib/flipper/poller.rb

No need to poll more than every 10 seconds currently. 
Also, this slows down requests to us by only polling every interval seconds regardless of how long the request took.

Adjust minimum poll and sleep interval for Cloud

---

lib/flipper/cloud/configuration.rb
lib/flipper/cloud/telemetry/instrumenter.rb
spec/flipper/cloud/configuration_spec.rb
spec/flipper/cloud_spec.rb
spec/flipper/engine_spec.rb

This turns on telemetry by default. 
Also, this turns off telemetry logging by default so its not annoying to people.

Enable telemetry by default

---

lib/flipper/cli.rb
spec/flipper/cli_spec.rb

This refactors the CLI to accept accept stdout/stderr args to be used for output. It also switches to just using `Bundler::UI` entirely for output.

CLI: Use provided stdout/stderr streams

---

lib/flipper/api/v1/decorators/feature.rb
lib/flipper/api/v1/decorators/gate.rb

Removes delegation and respond to for many features/gates.
```
Before
Calculating -------------------------------------
Typecast.to_json      1.567k (± 1.0%) i/s -      7.850k in   5.008514s
After
Calculating -------------------------------------
Typecast.to_json      2.493k (± 1.0%) i/s -     12.699k in   5.094881s
```

API Perf - Features#get

---

benchmark/active_record_adapter_ips.rb
lib/flipper/adapters/active_record.rb

I noticed `#features` was calling `Gate.all.map(&:key).to_set` to get the list of features, which will pull a lot of data over the wire to get the list of features. This replaces it with `Gate.distinct.pluck(:key).to_set`.  Thankfully, `#features` is not used in our hot code path internally (`get_all` with memoization is used when checking `#enabled?`), but this could have some impact for those with large actor sets.
```
$ ruby benchmarks/active_record_ips.rb
features      6.453k (± 8.3%) i/s -     32.604k in   5.088062s
features     10.130k (± 8.6%) i/s -     50.661k in   5.038290s
```
This benchmark uses an sqlite in-memory database, so the results should be even more dramatic over a network connection.

Micro optimization for `#features` on ActiveRecord adapter

---

lib/flipper.rb
lib/flipper/adapters/operation_logger.rb
lib/flipper/adapters/read_only.rb
lib/flipper/adapters/strict.rb
lib/flipper/adapters/wrapper.rb

This adds `Flipper::Adapters::Wrapper`, which can be used as a base class for an adapter that just wraps another adapter. By default, all methods delegate to the wrapped adapter. Implement `#wrap` to customize the behavior of all delegated methods, or override individual methods as needed.
```ruby
class MyNewAdapter < Flipper::Adapters::Wrapper
def enable(feature, gate, resource)
end
def wrap(method, *args, **kwargs)
if some_condition?(method)
yield # call original adapter method
else
end
end
end
```
And then you can configure Flipper to use the new adapter:
```
Flipper.configure do |config|
config.use MyNewAdapter
end
```

Add base class for wrapping another adapter

---

lib/flipper/cloud/telemetry.rb
spec/flipper/cloud/telemetry_spec.rb

So we can turn off however we like regardless of status code from the server side.

Add telemetry shutdown header

---

lib/flipper/spec/shared_adapter_specs.rb
lib/flipper/test/shared_adapter_test.rb

This refactors some of the adapter tests related to actors to use the feature interface instead of directly inspecting the adapters data. This change is needed for some work I'm doing to support large actor sets.

Refactor shared adapter test

---

lib/flipper/adapters/active_record.rb

This is a minor thing in my opinion.
I use `active_record_doctor` to identify potential database issues or risks.
When I run `$ bin/rake active_record_doctor` after I added `flipper-active_record`, I received the following recommendations:
```
add a `presence` validator to Flipper::Adapters::ActiveRecord::Gate.feature_key - it's NOT NULL but lacks a validator
add a `presence` validator to Flipper::Adapters::ActiveRecord::Gate.key - it's NOT NULL but lacks a validator
add a `presence` validator to Flipper::Adapters::ActiveRecord::Feature.key - it's NOT NULL but lacks a validator
```
Ref. <https://github.com/gregnavis/active_record_doctor?tab=readme-ov-file#detecting-missing-presence-validations>
This pull request adds these validators.

Add ActiveRecord validations to mirror table NOT NULL constraint

---

lib/flipper/adapter_builder.rb
lib/flipper/adapters/active_record.rb

Hello, I noticed the duplicate deletions in `Flipper::Adapters::ActiveRecord#set`
The `Flipper::Adapters::ActiveRecord#delete` already does the same `destroy_all`.

Remove redundant deletion of feature gate in Flipper::Adapters::ActiveRecord#set.

---

lib/flipper/adapters/active_record.rb
spec/flipper/adapters/active_record_spec.rb

The Flipper models are loading too soon and causing weirdness with saving models that have a belongs_to. The belongs_to association is being loaded on save even when there have not been any changes to the association.
BEFORE
```ruby
irb(main):001> token = OrganizationAccessToken.find(1)
...
irb(main):002> token.update(description: 'a token')
DEBUG:   TRANSACTION (0.7ms)  BEGIN
DEBUG:   Organization Load (1.0ms)  SELECT "organizations".* FROM "organizations" WHERE "organizations"."status" != $1 AND "organizations"."id" = $2 LIMIT $3  [["status", "deactivated"], ["id", 3], ["LIMIT", 1]]
DEBUG:   OrganizationAccessToken Update (1.0ms)  UPDATE "organization_access_tokens" SET "description" = $1, "updated_at" = $2 WHERE "organization_access_tokens"."id" = $3  [["description", "a token"], …
```

Fix: Respect Rails defaults in an initializer by delaying loading ActiveRecord adapter until framework is loaded

---

lib/flipper/adapters/active_record.rb

Related: https://github.com/flippercloud/flipper/pull/705
Refs:
- https://github.com/rails/rails/blob/b752c38e81a310c1aaca78c7cdd1784009ea189a/activerecord/lib/active_record/connection_handling.rb#L259
- https://github.com/rails/rails/blob/b752c38e81a310c1aaca78c7cdd1784009ea189a/activerecord/lib/active_record/connection_handling.rb#L293-L294
This will be soft deprecated in Rails 7.2.
The reason for this change is twofold.
1. We're running on Rails Edge with `active_record.permanent_connection_checkout = :deprecated` and this call to `#connection` was logged as a violation. Our goal is to configure this with `:disallowed` some day. Even if this needed to be a permanent checkout, `connection` should ideally be swapped with `lease_connection` (this would require a specific check to ensure …

Address soft deprecation of `ActiveRecord::Base.connection`

---

lib/flipper/adapters/active_record.rb
spec/flipper/adapters/active_record_spec.rb
spec/flipper/adapters/strict_spec.rb
spec/flipper/engine_spec.rb
spec/flipper/middleware/memoizer_spec.rb
spec/support/fail_on_output.rb
spec/support/spec_helpers.rb

The issue in #866 is tricky. For some reason when using the pg adapter, active record is poisoning the transaction on unique error even though that is specifically rescued. The error does not occur with sqlite or mysql. 🤷‍♂️
I asked copilot how to let AR and company know that the transaction is not poisoned and they suggested save points. And guess what... it worked! Haha. I don't love these two extra network calls but it does fix the issue for now. 
If anyone smarter or with more time can find a more slick solution or dig into why pg handles this different than sqlite/mysql I'm all ears. 
Initially I thought the problem was because of the connection check out stuff happening before the rescue but even moving the rescue inside with_connection block didn't fix the issue for pg.
refs #867 …

Active record poisoned transaction with postgres

---

lib/flipper/ui/views/feature.erb

A minor nuisance when enabling a feature for a group is that once you have quite a few groups, they show up in a random* order. IMO the UI would be easier to use if they showed alphabetically. 
| Before | After |
|-------|-------|
| ![image](https://github.com/user-attachments/assets/206b8707-e480-4928-aac6-515ac23df4d5) | ![image](https://github.com/user-attachments/assets/b58020c1-7524-4aee-97b7-c1124c32c9dc) |
* technically they show in the order they are defined in your code.
I only changed this at the view layer, I wasn't sure if you want to sort groups alphabetically everywhere they're interacted with.

Sort available groups alphabetically in UI

---

spec/flipper/cli_spec.rb

The `ostruct` gem will be a bundled gem in the future and needs to become a properly defined dependency because of that. There seems to be a general trend of just removing the `require "ostruct"` where possible.
It seems like this happened in one of the dependencies of Flipper, causing `OpenStruct` to no longer be available. As it was only used in a single place, I figured it's probably best to just remove its usage.

Remove usage of OpenStruct

---

.github/workflows/ci.yml
flipper-active_record.gemspec
flipper-active_support_cache_store.gemspec
test_rails/system/test_help_test.rb

This pull request relaxes the dependency requirements of flipper-active_record and flipper-active_support_cache_store to support Rails v8.x. This fixes #894.
It also adds Rails v8 and Rails v7.2 to the CI matrix.
Unfortunately, a lot of tests are currently failing, but the failures seem to be in line with the current failures on main.

Add support for Rails v8.x

---

lib/flipper/metadata.rb

Added your github sponsors link to `funding_uri` in metadata.rb for all the gemspecs to help increase visibility using the `bundle fund` command in Bundler.

Add funding_uri to metadata.rb

---

lib/flipper/feature.rb
spec/flipper/feature_spec.rb

Rejecting nil has the advantage of allowing use of null object patterns using objects that implement nil? but are not strictly nil. This also works well with the ['actor cannot be nil' guard clause](https://github.com/flippercloud/flipper/blob/main/lib/flipper/types/actor.rb#L12) which uses `nil?` to check nilness.
Just an idea. Would love to hear if there are other ideas. Could handle it differently further down by making Types::Actor.wrap(actor) return nil instead of throw an error. Not sure if that would have unintended affects.

Use reject(&:nil?) in enabled? check

---

lib/generators/flipper/setup_generator.rb
lib/generators/flipper/templates/initializer.rb
test_rails/generators/flipper/setup_generator_test.rb

This adds `config/initializers/flipper.rb` to the `flipper:setup` generator, which which documents the configuration options (and their defaults).

Generate a default initializer

---

Gemfile
examples/cloud/backoff_policy.rb
lib/flipper/cloud/configuration.rb
lib/flipper/cloud/telemetry.rb
lib/flipper/cloud/telemetry/backoff_policy.rb
lib/flipper/cloud/telemetry/submitter.rb
spec/flipper/cloud/telemetry/backoff_policy_spec.rb
spec/flipper/cloud/telemetry/submitter_spec.rb
spec/flipper/cloud/telemetry_spec.rb

The old version was attacking us. 
This version is much more "hey you are doing your best and i appreciate that so i'll chill over here while you have a moment."
It'll retry for around 5 minutes and queue up to 20 minutes (assuming 1 minute interval which is default).

Chill Out the Backoff Policy for Telemetry

---

lib/flipper/ui.rb
lib/flipper/ui/action.rb
lib/flipper/ui/actions/actors_gate.rb
lib/flipper/ui/actions/boolean_gate.rb
lib/flipper/ui/actions/features.rb
lib/flipper/ui/actions/groups_gate.rb
lib/flipper/ui/actions/percentage_of_actors_gate.rb
lib/flipper/ui/actions/percentage_of_time_gate.rb
lib/flipper/ui/util.rb
lib/flipper/ui/views/add_actor.erb
lib/flipper/ui/views/add_group.erb
lib/flipper/ui/views/feature.erb
lib/flipper/ui/views/features.erb
spec/flipper/ui/actions/actors_gate_spec.rb
spec/flipper/ui/actions/boolean_gate_spec.rb
spec/flipper/ui/actions/feature_spec.rb
spec/flipper/ui/actions/features_spec.rb
spec/flipper/ui/actions/groups_gate_spec.rb
spec/flipper/ui/actions/percentage_of_actors_gate_spec.rb
spec/flipper/ui/actions/percentage_of_time_gate_spec.rb

Fixes #901. Likely fixes all the rack protection issues people have. I realized that rack protection includes several things by default unless you exclude them. My bad. I thought I was only "use"-ing authenticity token. Hopefully this fixes some issues for others because now that is all I'm using.

Big pass on escaping and urls

---

lib/generators/flipper/templates/initializer.rb

Corrects a minor typo in the Flipper initializer template (`adaper` → `adapter`).

docs: fix typo in Flipper initializer template

---

lib/flipper/adapters/active_record.rb

The last version removed the on_load wrapper, making flipper load ActiveRecord immediately whenever flipper is required. This causes some issues with other gems that setup their own behavior using `on_load`.
This reintroduces the on_load wrapper around the database models, which by inheriting from ActiveRecord::Base were causing ActiveRecord to be loaded at require time.
Papertrail, for example, [loads its activerecord code in an `on_load` hook](https://github.com/paper-trail-gem/paper_trail/blob/master/lib/paper_trail/frameworks/rails/railtie.rb#L25-L27). If the flipper gem is loaded first, AR will be loaded and its hooks will run before papertrail has setup its hook, meaning that papertrail's code will never run.
`on_load` was removed in #924, in a commit that reads "Now that we are …

Do not load ActiveRecord at require time
