flippercloud/flipper

README.md, lib/flipper/dsl.rb, lib/flipper/feature.rb, lib/flipper/gate_values.rb, lib/flipper/gates/actor.rb, lib/flipper/gates/boolean.rb, lib/flipper/gates/group.rb, lib/flipper/gates/percentage_of_actors.rb, lib/flipper/gates/percentage_of_random.rb, lib/flipper/types/actor.rb, lib/flipper/types/group.rb, lib/flipper/types/percentage.rb, spec/flipper/dsl_spec.rb, spec/flipper/feature_spec.rb, spec/flipper/gate_values_spec.rb, spec/flipper/gates/boolean_spec.rb, spec/flipper/gates/percentage_of_actors_spec.rb, spec/flipper/gates/percentage_of_random_spec.rb, spec/flipper/types/group_spec.rb, spec/flipper/types/percentage_spec.rb, spec/helper.rb
Adding more convenience methods for Feature to make it easier to get what is enabled and what the state of things is.
I'm going to add some convenience methods for enable_actor, enable_group, etc. and their disable counterparts as well. I'll probably also add those to the DSL. I'm also going to move most of the typecasting into the types or GateValue. Going to see how it feels.
fyi @rsanheim @aroben so we don't double work. Hoping to finish this up tomorrow. Feel free to review anything here, though it is not quite final.
=> WIP: More Features for Feature 

lib/flipper/feature.rb, spec/flipper/feature_spec.rb
=> Add enabled/disables_gates

lib/flipper/feature.rb, lib/flipper/gates/boolean.rb, lib/flipper/type.rb, spec/flipper/feature_spec.rb, spec/flipper/gates/boolean_spec.rb
=> Make percentages enabled to 100 return state of :on

lib/flipper/adapters/pstore.rb, spec/flipper/adapters/pstore_spec.rb, spec/helper.rb
=> Add pstore adapter

.travis.yml, Gemfile, Rakefile, docs/redis/README.md, examples/redis/basic.rb, examples/redis/internals.rb, flipper-redis.gemspec, flipper-ui.gemspec, flipper.gemspec, lib/flipper-redis.rb, lib/flipper/adapters/redis.rb, spec/flipper/adapters/redis_spec.rb
Keeping it as separate gem, just like flipper-ui.
=> Merge flipper-redis in to repo

lib/flipper/ui.rb
Will fix #117 .  Not sure if this is the _best_ way, but works for now.  Reference #117 for conversation about why I think this works for now. Curious to hear what everyone thinks
With this change:
=> override inspect on Rack::Builder for pretty rake routes output

spec/flipper/instrumentation/statsd_subscriber_spec.rb
Fixes #155 
Looks like master build is failing as of commit fdbae94 
https://travis-ci.org/jnunemaker/flipper/builds/148951733
This fixes it
=> require statsd & instrumented adapter in failing spec

README.md
So people can see the faces behind the project. :smile:
fyi @AlexWheeler
=> Add brought to you by

lib/flipper/api/middleware.rb, lib/flipper/api/v1/actions/percentage_of_time_gate.rb, spec/flipper/api/v1/actions/percentage_of_time_gate_spec.rb
* POST / to enable  with percentage parameter
* DELETE to disable
re: discussion in #168, after this I'll get a PR up for updating status code for percentage_invalid from 400 -> 422 for the ErrorResponse and the endpoints specs because it is more fitting
=> add api v1 percentage_of_time endpoint

docs/api/README.md
=> adds documentation for api v1 percentage of time gate

README.md
fyi @lazebny. I've also added you to the repo as a collaborator. If you ever want to stop or stop using docker, just let me know and I'll remove you. Same flow, create pull requests and I'll review them, but now you can do so right on the repo. Thanks!
=> Add lazebny as the docker person

flipper-sequel.gemspec, lib/flipper-sequel.rb, lib/flipper/adapters/sequel.rb, lib/generators/flipper/templates/sequel_migration.rb, spec/flipper/adapters/sequel_spec.rb
Hey, 
First commit allows not install mongo, memcached, redis, gems in local environment. All tests suite is spining up in docker containers and this could be reached with 1 command. Please check in README.md file.
Second commit add sequel adapter.
=> Add sequel adapter

lib/flipper/adapters/active_record.rb, lib/flipper/adapters/redis.rb
* ActiveRecord#enable
* Redis#enable
=> fixes minor docs typo

docs/active_record/README.md
updates docs to show support for active record 5.0.x
removes trailing whitespace
=> Update Active Record adapter docs to show support for Rails 5.0.x

docs/Adapters.md, docs/read-only/README.md
=> Add read-only adapter docs

docs/Adapters.md
@jnunemaker 
Quick win. Hope this helps.
=> fixes broken link pointing to the read-only documentation

lib/flipper/adapters/http/client.rb, spec/flipper/adapters/http_spec.rb
=> HTTP Adapter User Agent

lib/flipper/adapters/http.rb, spec/flipper/adapters/http_spec.rb
Follow up for #244 that uses the new param for the http adapter.
=> Allow Http Adapter to Enable/Disable Unregistered Groups

examples/cloud/basic.rb, flipper-cloud.gemspec, lib/flipper-cloud.rb, lib/flipper/cloud.rb, spec/flipper/cloud_spec.rb
WHAAAAAT! Nothing much to see, just some prep work...
=> Add flipper cloud

lib/flipper/dsl.rb, lib/flipper/errors.rb, lib/flipper/gates/group.rb
fixes #262
* This error is no longer raised since it was removed in commit 0d314c54affc2077806a0cc62cfd1d043381afe1.
=> Remove GruopNotRegistered error and doc

docs/Adapters.md, docs/cache_store/README.md
Addresses #266 
Adds CacheStore Docs
=> Add CacheStore docs with examples of cache + adapter

examples/active_record/basic.rb
Adds comment indicating the need for a separate gem. #287
=> Adds a comment.

docs/rollout/README.md
=> Document Rollout adapter

lib/flipper/adapters/pstore.rb
PStore's thread_safe option  (fixes https://github.com/jnunemaker/flipper/issues/316)
=> Update PStore adapter with thread_safe option

lib/flipper/adapters/sync/interval_synchronizer.rb, spec/flipper/adapters/sync/interval_synchronizer_spec.rb
This was intermittently failing. Now it won't.
=> Switch now_ms to now (seconds)

docs/Adapters.md, docs/moneta/README.md
documents the moneta adapter #364
=> document moneta adapter

lib/flipper.rb, lib/flipper/dsl.rb, lib/flipper/feature.rb, spec/flipper/dsl_spec.rb, spec/flipper/feature_spec.rb, spec/flipper_spec.rb
=> Add exist to feature, dsl and flipper default instance delegation

docs/Gates.md
Described in documentation gates order is different from actual implementation after PR #370.
=> Update gates order documentation.

docs/api/README.md
=> Document flipper api actor endpoint

lib/flipper/adapters/active_record.rb
=> Replace delete_all with destroy_all in ActiveRecord adapter

lib/flipper/ui/configuration.rb, lib/flipper/ui/views/features.erb, spec/flipper/ui/actions/features_spec.rb, spec/flipper/ui/configuration_spec.rb
Hello,
I find it funny but I'm just not fond of the art of Taylor Swift and the huge preview scares me every time :)
Feedback on the documentation/UI copies are welcome!
Follow-up for #384
Also a solution for #398
=> Add configuration option to disable features added just for fun

docs/ui/README.md
I ran into an issue (#414) when setting up Flipper with lazy loading.
It wasn't clear to me what code should go in the block, or that this is an alternative to the standard initialization approach.
=> flipper-ui: Clarify setup instructions for lazy loading

lib/flipper/adapters/active_record.rb
In #420 it was brought up that some AR unique errors were popping up for people. This should help with those.
=> ActiveRecord Idempotency

docs/ui/README.md
Documentation for configuration option introduced in #413
=> Add documentation about how to disable fun mode

Changelog.md
Adds docs on things you can remove when upgrading to 0.21.
=> 0.21 Changelog

docs/api/README.md
Fixes typo `flipper` -> `Flipper`
=> Fix casing of flipper to Flipper

docs/mongo/README.md
I think this example will save others the time I wasted messing around. Eventually @phstc's example in #90.
=> Added Mongoid example

spec/flipper/railtie_spec.rb
Hey, I'm a big user of Flipper and was looking through the new Flipper middleware.  I saw a few opportunities to simplify this spec. Open to any of this?
=> railtie spec

lib/flipper/adapters/dual_write.rb, lib/flipper/adapters/memoizable.rb, lib/flipper/adapters/sync.rb
I discovered `.tap` a while back and it was a game changer.  shall we simplify?
https://apidock.com/ruby/Object/tap
=> tap-it-good

Changelog.md
improve messaging around breaking change
=> changelog update

flipper-dalli.gemspec, spec/flipper/adapters/active_support_cache_store_spec.rb, spec/flipper/middleware/memoizer_spec.rb
=> [flipper-dalli] Relax dalli version constraint

Changelog.md, lib/flipper/dsl.rb, spec/flipper/dsl_spec.rb
=> feat(dsl): make it possible to disable internal memoization

Gemfile, spec/spec_helper.rb
debug gem is the new gold standard.
=> Use debug gem instead of pry

Changelog.md, lib/flipper/adapters/active_record.rb
=> ActiveRecord: use gate_class for #get_all

flipper-ui.gemspec
3 is out and it works fine.
closes #674
=> Update rack protection to < 4

examples/ui/read_only.ru, lib/flipper/ui/action.rb, lib/flipper/ui/actions/actors_gate.rb, lib/flipper/ui/actions/add_feature.rb, lib/flipper/ui/actions/boolean_gate.rb, lib/flipper/ui/actions/feature.rb, lib/flipper/ui/actions/features.rb, lib/flipper/ui/actions/groups_gate.rb, lib/flipper/ui/actions/percentage_of_actors_gate.rb, lib/flipper/ui/actions/percentage_of_time_gate.rb, lib/flipper/ui/configuration.rb, lib/flipper/ui/views/feature.erb, lib/flipper/ui/views/features.erb, lib/flipper/ui/views/read_only.erb
This adds one option to make the UI read only. I've been kind of wanting this for a while. It shows things and explains and also denies in the actions.
closes #678
=> Read only UI

script/examples
=> Fix script/examples

lib/flipper/adapters/memory.rb
After discussing with @jnunemaker yesterday, there were a few instances in #702 where we weren't sure if reads needed to be protected. Easiest way to be sure is just wrap all reads in a lock. concurrent-ruby's `ReadWriteLock` will block any writes if there's an active read lock.
=> Use Concurrent::ReadWriteLock in Memory adapter

lib/flipper/middleware/memoizer.rb, spec/flipper/middleware/memoizer_spec.rb
This enhances preload to support customizing preloading per request. Should solve the problems in https://github.com/flippercloud/flipper/discussions/729#discussioncomment-5876084.
=> preload via block

lib/flipper/adapters/http/client.rb, spec/flipper/adapters/http_spec.rb
I was digging through the code and saw some opportunities to simplify...functionally equivalent   🎯
=> simplify http adapter

flipper-moneta.gemspec
Several new versions since 1.2.
=> Relax moneta version

lib/flipper/api/middleware.rb, spec/flipper/api_spec.rb
Now I can use this to name the app signal or new relic route or whatever.
=> Add action class and method to api env

lib/flipper/serializers/gzip.rb, lib/flipper/serializers/json.rb, lib/flipper/typecast.rb
Make it easier to instrument some methods from outside of flipper.
=> Easier instrumenting of typecasting/serializers

lib/flipper/api/v1/decorators/actor.rb, lib/flipper/api/v1/decorators/feature.rb
=> Move delegate require to correct file

lib/flipper/ui/views/features.erb
Followup to #851 to tweak a few styles after some testing.
=> UI: Tweak classes on feature list

Gemfile
=> Add pstore for ruby 3.3.x

flipper-ui.gemspec
s. https://github.com/rgrove/sanitize/blob/main/CHANGELOG.md#700-2024-12-29
=> Relax sanitize version constraint

lib/flipper/ui.rb
Some people are using this so let's make it work backwords compatibly however they were. 
refs #915
=> Make rack_protection key work again for flipper ui

lib/flipper/cloud/configuration.rb, lib/flipper/instrumentation/log_subscriber.rb
Just a couple that need to be appended to.
=> Fix frozen strings for ruby 3.4

lib/flipper/adapters/active_record.rb
This lazy loads the column check so a connection is not needed at boot time.
=> ActiveRecord Loading Stuff

lib/flipper/adapters/active_record.rb, lib/flipper/adapters/sequel.rb
This simply fixes a small grammatical issue seen in a couple of locations.
=> Fix grammatical issue ("needs migrated")
